// ignore_for_file: lines_longer_than_80_chars
import 'destination_detail_entry.dart';

/// 2. Wilayah Bali & Nusa Tenggara (ID 16-25)
final List<DestinationDetailEntry> baliNusaDetails = [
  // 16. Ubud Cultural Sanctuary
  DestinationDetailEntry(
    id: 16,
    shortDescription: 'Pusat seni, spiritualitas, yoga, dan sawah berundak ikonik Tegalalang di jantung perbukitan hijau pulau Bali.',
    attractions: [
      {
        'id': '1',
        'name': 'Terasering Sawah Tegalalang',
        'description': 'Sawah berundak bertingkat sistem irigasi Subak UNESCO dengan ayunan raksasa berlatar lembah pohon kelapa.',
        'image': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Sacred Monkey Forest Sanctuary',
        'description': 'Cagar alam hutan lindung dengan candi suci kuno yang dihuni ratusan kera ekor panjang (Macaca fascicularis).',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi & Cagar Budaya',
        'estimated_cost': 80000,
        'source': 'https://monkeyforestubud.com/',
      },
      {
        'id': '3',
        'name': 'Puri Saren Agung & Campuhan Ridge Walk',
        'description': 'Istana Kerajaan Ubud dan jalur jalan santai di atas bukit punggung naga berhawa sejuk berlatar ilalang hijau.',
        'image': 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Budaya & Trekking',
        'estimated_cost': 0,
        'source': 'https://balitourismboard.or.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Mandapa, a Ritz-Carlton Reserve',
        'type': 'Luxury Resort',
        'location': 'Jl. Kedewatan, Banjar Kedewatan, Ubud',
        'price_range': 'Rp12.000.000 - Rp24.000.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ritzcarlton.com/mandapa',
      },
      {
        'id': '2',
        'name': 'Bambu Indah Eco-Resort',
        'type': 'Eco-Resort',
        'location': 'Jl. Baung, Sayan, Ubud',
        'price_range': 'Rp2.500.000 - Rp5.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bambuindah.com/',
      },
      {
        'id': '3',
        'name': 'Komaneka at Monkey Forest',
        'type': 'Resort',
        'location': 'Jl. Monkey Forest, Ubud',
        'price_range': 'Rp1.800.000 - Rp3.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://komaneka.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Bebek Bengil / Bebek Betutu Ubud',
        'description': 'Bebek krispi renyah atau bebek ungkep bumbu base genep 16 rempah khas Bali disajikan dengan sambal matah segar.',
        'price_range': 'Rp85.000 - Rp150.000',
        'location': 'Jl. Hanoman, Padangtegal, Ubud',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bebekbengil.co.id/',
      },
      {
        'id': '2',
        'name': 'Nasi Campur Ayam Kedewatan Ibu Mangku',
        'description': 'Nasi campur khas Bali dengan ayam suwir pedas, sate lilit ikan, lawar nangka, telur bumbu bali, dan kacang goreng.',
        'price_range': 'Rp35.000 - Rp55.000',
        'location': 'Jl. Raya Kedewatan No.18, Ubud',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://balitourismboard.or.id/',
      },
      {
        'id': '3',
        'name': 'Tipat Cantok Ubud',
        'description': 'Kupat tahu sayur khas Bali berpadu kangkung, kacang panjang, tauge, dan tahu disiram bumbu kacang kencur sedap.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Pasar Tradisional Ubud',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 17. Pura Luhur Uluwatu
  DestinationDetailEntry(
    id: 17,
    shortDescription: 'Pura laut di pucuk tebing karang terjal setinggi 70 meter di atas Samudra Hindia dengan pertunjukan Tari Kecak magis saat sunset.',
    attractions: [
      {
        'id': '1',
        'name': 'Tari Kecak & Api Sunset Uluwatu',
        'description': 'Pertunjukan seni drama tari Kecak Ramayana berlatar langsung lingkaran matahari terbenam ke samudra biru.',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Pertunjukan Budaya',
        'estimated_cost': 150000,
        'source': 'https://disparda.badungkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Tebing Karang Purba Samudra Hindia',
        'description': 'Jalur setapak batu bertembok di tepian tebing karang kapur dengan deburan ombak laut lepas yang dahsyat.',
        'image': 'https://images.unsplash.com/photo-1697931728907-ae18fd18d864?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Tebing',
        'estimated_cost': 50000,
        'source': 'https://disparda.badungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pantai Suluban (Blue Point Beach)',
        'description': 'Gua karang tersembunyi dengan jalur sempit menuju pantai ombak kelas dunia bagi para peselancar mancanegara.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai & Surfing',
        'estimated_cost': 10000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Bulgari Resort Bali',
        'type': 'Luxury Resort',
        'location': 'Jl. Goa Lempeh, Banjar Dinas Kangin, Pecatu',
        'price_range': 'Rp14.000.000 - Rp28.000.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bulgarihotels.com/bali',
      },
      {
        'id': '2',
        'name': 'Anantara Uluwatu Bali Resort',
        'type': 'Resort',
        'location': 'Jl. Pemutih, Labuan Sait, Pecatu',
        'price_range': 'Rp3.800.000 - Rp7.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://anantara.com/uluwatu-bali',
      },
      {
        'id': '3',
        'name': 'Uluwatu Surf Villas',
        'type': 'Villa',
        'location': 'Jl. Pantai Suluban, Pecatu',
        'price_range': 'Rp1.900.000 - Rp4.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://uluwatusurfvillas.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Seafood Jimbaran Grill Bakar Arang',
        'description': 'Ikan kakap, lobster, dan kepiting dibakar dengan bumbu pasta cabai tomat khas Bali di tepi pasir pantai.',
        'price_range': 'Rp80.000 - Rp200.000',
        'location': 'Pantai Jimbaran & Muaya, Badung',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparda.badungkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Sate Lilit Ikan Laut Bumbu Bali',
        'description': 'Daging ikan laut cincang berbumbu serai, kelapa parut, daun jeruk, dan santan yang dililitkan pada batang serai.',
        'price_range': 'Rp30.000 - Rp50.000',
        'location': 'Pecatu & Jimbaran',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://balitourismboard.or.id/',
      },
      {
        'id': '3',
        'name': 'Nasi Campur Pedas Pecatu',
        'description': 'Nasi campur lauk ayam suwir betutu, sayur urap daun singkong, kacang goreng, dan sambal matah ekstra pedas.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Jl. Labuan Sait, Pecatu',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 18. Desa Penglipuran
  DestinationDetailEntry(
    id: 18,
    shortDescription: 'Desa adat terbersih di dunia di dataran tinggi Bangli dengan tata ruang Tri Mandala dan lorong bambu asri.',
    attractions: [
      {
        'id': '1',
        'name': 'Lorong Rumah Tradisional Bebas Polusi',
        'description': 'Jalanan paving batu tertata rapi bebas kendaraan bermotor dengan gerbang angkul-angkul simetris khas Bali.',
        'image': 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800&auto=format&fit=crop',
        'category': 'Desa Adat & Budaya',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Hutan Bambu Lindung Penglipuran',
        'description': 'Hutan bambu lestari seluas 45 hektar yang asri dan sejuk, berfungsi sebagai penyerap air dan benteng ekologi desa.',
        'image': 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop',
        'category': 'Ekowisata Alam',
        'estimated_cost': 0,
        'source': 'https://banglikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pura Penataran Penglipuran',
        'description': 'Pura utama di zona Utama Mandala dengan arsitektur bebatuan hitam berundak di bagian tertinggi desa.',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Suci',
        'estimated_cost': 0,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Penglipuran Traditional Homestay',
        'type': 'Homestay',
        'location': 'Jl. Penglipuran, Kubu, Bangli',
        'price_range': 'Rp300.000 - Rp600.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banglikab.go.id/',
      },
      {
        'id': '2',
        'name': 'The Kayon Jungle Resort',
        'type': 'Resort',
        'location': 'Banjar Bresela, Payangan, Gianyar',
        'price_range': 'Rp4.500.000 - Rp9.000.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://thekayonjungleresort.com/',
      },
      {
        'id': '3',
        'name': 'Taman Prakerti Bhuana Homestay',
        'type': 'Guesthouse',
        'location': 'Beng, Gianyar / Bangli',
        'price_range': 'Rp350.000 - Rp700.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://balitourismboard.or.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Loloh Cemcem Penglipuran',
        'description': 'Minuman herbal tradisional segar terbuat dari daun cemcem, air kelapa muda, kayu manis, dan gula aren berkhasiat.',
        'price_range': 'Rp5.000 - Rp10.000 / botol',
        'location': 'Rumah Warga Desa Penglipuran',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banglikab.go.id/',
      },
      {
        'id': '2',
        'name': 'Tipat Blayag Bangli',
        'description': 'Ketupat janur panjang disiram kuah kari kuning kental kaya rempah dengan suwiran ayam, urap, dan rempeyek.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Pasar Senggol Bangli',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://balitourismboard.or.id/',
      },
      {
        'id': '3',
        'name': 'Mujair Nyat-Nyat Kintamani',
        'description': 'Ikan mujair danau Batur dimasak bumbu rempah lengkap Bali (bumbu nyat-nyat) hingga air meresap pekat pedas gurih.',
        'price_range': 'Rp35.000 - Rp55.000',
        'location': 'Kintamani / Bangli',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 19. Nusa Penida (Kelingking Beach)
  DestinationDetailEntry(
    id: 19,
    shortDescription: 'Tebing karang kapur raksasa berbentuk kepala T-Rex yang menjorok ke perairan samudra toska di pulau Nusa Penida.',
    attractions: [
      {
        'id': '1',
        'name': 'T-Rex Viewpoint Kelingking Secret Point',
        'description': 'Titik pandang panorama puncak tebing kapur ikonik dengan pemandangan lekukan pantai pasir putih tersembunyi di bawah.',
        'image': 'https://images.unsplash.com/photo-1697931728907-ae18fd18d864?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Tebing Ikonik',
        'estimated_cost': 25000,
        'source': 'https://balitourismboard.or.id/',
      },
      {
        'id': '2',
        'name': 'Broken Beach (Pasih Uug) & Angel’s Billabong',
        'description': 'Jembatan tebing melengkung alami di atas laut serta kolam renang alami air pasang jernih berpemandangan samudra.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Formasi Geologi Unik',
        'estimated_cost': 15000,
        'source': 'https://klungkungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Snorkeling Manta Point & Crystal Bay',
        'description': 'Berenang dan menyelam bersama kawanan ikan Pari Manta raksasa di perairan jernih Nusa Penida.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari & Diving',
        'estimated_cost': 200000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Maua Nusa Penida Bali',
        'type': 'Luxury Resort',
        'location': 'Sakti, Nusa Penida, Klungkung',
        'price_range': 'Rp3.200.000 - Rp6.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://mauahotels.com/',
      },
      {
        'id': '2',
        'name': 'Semabu Hills Hotel Nusa Penida',
        'type': 'Hotel',
        'location': 'Toyapakeh, Nusa Penida',
        'price_range': 'Rp950.000 - Rp1.800.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://semabuhills.com/',
      },
      {
        'id': '3',
        'name': 'Bintang Bungalow Nusa Penida',
        'type': 'Bungalow',
        'location': 'Crystal Bay Road, Sakti',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://klungkungkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Tongkol Bakar Sambal Matah Penida',
        'description': 'Ikan laut tongkol/cakalang segar tangkapan nelayan lokal dipanggang arang batok kelapa dengan sambal matah serai melimpah.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Toyapakeh & Crystal Bay',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://balitourismboard.or.id/',
      },
      {
        'id': '2',
        'name': 'Ledok Nusa Penida',
        'description': 'Bubur tradisional khas Nusa Penida berbahan jagung, singkong, kacang merah, dan aneka sayuran dengan bumbu rempah harum.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Warung Tradisional Nusa Penida',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://klungkungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Kelapa Muda Dingin Pesisir Kelingking',
        'description': 'Air kelapa muda manis alami disajikan langsung dari batoknya untuk menyegarkan stamina usai menuruni tangga tebing.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Kios Kelingking Beach',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 20. Gunung Rinjani & Segara Anak
  DestinationDetailEntry(
    id: 20,
    shortDescription: 'Gunung berapi tertinggi kedua di Indonesia berketinggian 3.726 mdpl dengan danau kaldera biru toska Segara Anak dan Gunung Barujari.',
    attractions: [
      {
        'id': '1',
        'name': 'Danau Kaldera Segara Anak & Air Panas Aik Kalak',
        'description': 'Danau kawah vulkanik indah seluas 11 juta m² dengan sumber mata air panas alami untuk pemulihan tubuh pendaki.',
        'image': 'https://images.unsplash.com/photo-1698799330469-e53f68a91c08?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Kaldera',
        'estimated_cost': 150000,
        'source': 'https://rinjaninationalpark.id/',
      },
      {
        'id': '2',
        'name': 'Summit Attack Puncak Rinjani 3.726 MDPL',
        'description': 'Pendakian puncak berbatu pasir menantang sebelum fajar untuk menyaksikan matahari terbit berlatar Gunung Agung Bali.',
        'image': 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=800&auto=format&fit=crop',
        'category': 'Pendakian Ekstrem',
        'estimated_cost': 50000,
        'source': 'https://rinjaninationalpark.id/',
      },
      {
        'id': '3',
        'name': 'Plawangan Sembalun & Senaru',
        'description': 'Bibir kawah kemah utama dengan panorama spektakuler matahari terbenam di atas samudera awan putih.',
        'image': 'https://images.unsplash.com/photo-1518458628499-27acd7f2c893?q=80&w=800&auto=format&fit=crop',
        'category': 'Camping & Panorama',
        'estimated_cost': 0,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Rinjani Lodge Senaru',
        'type': 'Lodge',
        'location': 'Jl. Pariwisata Senaru, Bayan, Lombok Utara',
        'price_range': 'Rp1.100.000 - Rp2.200.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rinjanilodge.com/',
      },
      {
        'id': '2',
        'name': 'Sembalun Kita Cottage',
        'type': 'Cottage',
        'location': 'Sembalun Bumbung, Lombok Timur',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.ntbprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Nusantara Hotel Sembalun',
        'type': 'Hotel',
        'location': 'Jl. Raya Sembalun Lawang, Lombok Timur',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rinjaninationalpark.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ayam Taliwang Lombok Pedas Mantap',
        'description': 'Ayam kampung muda bakar berbumbu cabai rawit merah, terasi lombok, kemiri, kencur, disajikan dengan plecing kangkung.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Senaru & Mataram',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.ntbprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Plecing Kangkung Khas Lombok',
        'description': 'Kangkung lombok berbatang renyah dengan sambal tomat terasi bakar pedas, tauge, kacang tanah goreng, dan tetesan jeruk limau.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Sembalun & Senaru',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://lomboktimurkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Kopi Sembalun Arabika Gunung',
        'description': 'Kopi arabika single origin hasil kebun vulkanik Sembalun di ketinggian 1.200 mdpl dengan citarasa fruity segar.',
        'price_range': 'Rp15.000 - Rp30.000',
        'location': 'Desa Sembalun Lawang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 21. Gili Trawangan
  DestinationDetailEntry(
    id: 21,
    shortDescription: 'Pulau tropis bebas polusi kendaraan bermotor di Lombok Utara dengan pantai pasir putih, terumbu karang penyu, dan sunset bar meriah.',
    attractions: [
      {
        'id': '1',
        'name': 'Snorkeling Turtle Point Gili Trawangan',
        'description': 'Berenang berdampingan dengan penyu hijau liar di terumbu karang dangkal air laut sebening kaca.',
        'image': 'https://images.unsplash.com/photo-1705493583368-b25860b426a3?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 150000,
        'source': 'https://dispar.ntbprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Keliling Pulau Naik Sepeda & Cidomo',
        'description': 'Menyusuri jalan lingkar pesisir pulau sepanjang 7 km menikmati hembusan angin laut dan deretan pohon kelapa.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Aktivitas Santai',
        'estimated_cost': 50000,
        'source': 'https://lombokutarakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Sunset Swing Ombak Sunset Point',
        'description': 'Ayunan kayu di tengah air laut dangkal tepi pantai barat untuk mengabadikan momen matahari terbenam ke samudra.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Spot Foto Sunset',
        'estimated_cost': 0,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Hotel Villa Ombak Gili Trawangan',
        'type': 'Resort',
        'location': 'Gili Trawangan, Pemenang, Lombok Utara',
        'price_range': 'Rp1.100.000 - Rp2.500.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://hotelvillaombak.com/',
      },
      {
        'id': '2',
        'name': 'Pondok Santi Estate Gili Trawangan',
        'type': 'Luxury Estate',
        'location': 'Pesisir Selatan Gili Trawangan',
        'price_range': 'Rp2.800.000 - Rp5.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pondoksanti.com/',
      },
      {
        'id': '3',
        'name': 'Gili Eco Villas',
        'type': 'Eco-Villa',
        'location': 'Pesisir Utara Gili Trawangan',
        'price_range': 'Rp1.300.000 - Rp2.700.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://giliecovillas.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kakap Bakar Pasar Malam Gili Trawangan',
        'description': 'Pasar kuliner malam dengan aneka seafood segar yang dibakar langsung dengan sambal matah dan saus garlic butter.',
        'price_range': 'Rp45.000 - Rp85.000',
        'location': 'Night Market Gili Trawangan',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.ntbprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Sate Bulayak Khas Sasak',
        'description': 'Sate daging sapi berbumbu kari pedas disajikan dengan bulayak (lontong lilit daun enau khas Lombok).',
        'price_range': 'Rp25.000 - Rp40.000',
        'location': 'Pesisir Gili Trawangan & Senggigi',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://lombokutarakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Tropical Dragonfruit Smoothie Bowl',
        'description': 'Mangkok smoothie buah naga merah segar bertabur granola renyah, chia seeds, dan potongan kelapa muda.',
        'price_range': 'Rp35.000 - Rp55.000',
        'location': 'Beach Cafe Gili Trawangan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 22. Mandalika & Pantai Tanjung Aan
  DestinationDetailEntry(
    id: 22,
    shortDescription: 'Kawasan Ekonomi Khusus pariwisata berkelas dunia di Lombok Selatan dengan Sirkuit Internasional MotoGP, bukit Merese, dan pasir merica Tanjung Aan.',
    attractions: [
      {
        'id': '1',
        'name': 'Bukit Merese Sunset Viewpoint',
        'description': 'Bukit padang rumput hijau menjorok ke laut lepas dengan pemandangan 360 derajat teluk Tanjung Aan dan Samudra Hindia.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Perbukitan',
        'estimated_cost': 15000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Pantai Pasir Merica Tanjung Aan & Batu Payung',
        'description': 'Pantai berbentuk bulan sabit berair toska tenang dengan butiran pasir unik berukuran bulat mirip biji merica.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai Pasir Unik',
        'estimated_cost': 10000,
        'source': 'https://lomboktengahkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pertamina Mandalika International Circuit',
        'description': 'Sirkuit balap jalan raya internasional kelas dunia yang menggelar kejuaraan bergengsi MotoGP dan WSBK.',
        'image': 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?q=80&w=800&auto=format&fit=crop',
        'category': 'Olahraga Otomotif',
        'estimated_cost': 50000,
        'source': 'https://themandalikagp.com/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Pullman Lombok Merujani Mandalika Beach Resort',
        'type': 'Luxury Resort',
        'location': 'Kawasan ITDC Mandalika, Kuta, Pujut',
        'price_range': 'Rp1.900.000 - Rp4.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pullman-lombok-mandalika.com/',
      },
      {
        'id': '2',
        'name': 'Novotel Lombok Resort and Villas',
        'type': 'Resort',
        'location': 'Pantai Putri Nyale, Pujut, Lombok Tengah',
        'price_range': 'Rp1.200.000 - Rp2.800.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://novotellombok.com/',
      },
      {
        'id': '3',
        'name': 'Sikara Lombok Hotel',
        'type': 'Boutique Hotel',
        'location': 'Kuta, Pujut, Lombok Tengah',
        'price_range': 'Rp650.000 - Rp1.200.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sikaralombok.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Nasi Balap Puyung Inaq Esun',
        'description': 'Nasi hangat dengan suwiran ayam pedas membakar, kedelai goreng renyah, serundeng, dan sambal belut gurih khas Lombok Tengah.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Puyung & Kuta Mandalika',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://lomboktengahkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Beberuk Terong Khas Sasak',
        'description': 'Lalapan terong gelatik mentah dan kacang panjang berbalut sambal tomat terasi segar bercita rasa pedas asam segar.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Kuta Lombok',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.ntbprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Ikan Laut Bakar Bumbu Rajang',
        'description': 'Ikan baronang laut selatan segar dipanggang dengan olesan bumbu rajang rempah kunyit serai khas suku Sasak.',
        'price_range': 'Rp45.000 - Rp80.000',
        'location': 'Pesisir Pantai Tanjung Aan & Kuta',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 23. Taman Nasional Komodo (Pulau Padar)
  DestinationDetailEntry(
    id: 23,
    shortDescription: 'Habitat kadal purba terbesar di dunia (Varanus komodoensis) dengan bukit savana dramatis tiga warna teluk di Pulau Padar.',
    attractions: [
      {
        'id': '1',
        'name': 'Puncak Viewpoint Pulau Padar Tiga Teluk',
        'description': 'Mendaki 800 anak tangga batu untuk menikmati lanskap dunia tiga lekukan teluk berpasir putih, merah muda, dan hitam.',
        'image': 'https://images.unsplash.com/photo-1736523076168-fdda4640f1d8?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Savana Spektakuler',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Trekking Komodo di Pulau Rinca & Komodo',
        'description': 'Menyusuri savana liar bersama ranger profesional untuk mengamati komodo purba di habitat aslinya.',
        'image': 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=800&auto=format&fit=crop',
        'category': 'Pengamatan Satwa Purba',
        'estimated_cost': 120000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Pink Beach (Pantai Merah Muda) & Snorkeling',
        'description': 'Pantai pasir berwarna merah muda alami dari serpihan koral merah mikroskopis (Foraminifera) dan taman laut jernih.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Fenomena Pantai Langka',
        'estimated_cost': 50000,
        'source': 'https://manggaraibaratkab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'AYANA Komodo Waecicu Beach',
        'type': 'Luxury Resort',
        'location': 'Pantai Waecicu, Labuan Bajo, Flores',
        'price_range': 'Rp3.800.000 - Rp8.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ayana.com/labuan-bajo',
      },
      {
        'id': '2',
        'name': 'Plataran Komodo Resort & Spa',
        'type': 'Resort',
        'location': 'Pantai Waecicu, Labuan Bajo',
        'price_range': 'Rp4.500.000 - Rp9.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://plataran.com/komodo-resort/',
      },
      {
        'id': '3',
        'name': 'Meruorah Labuan Bajo',
        'type': 'Hotel',
        'location': 'Kawasan Marina Labuan Bajo, Jl. Soekarno Hatta',
        'price_range': 'Rp1.600.000 - Rp3.200.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://meruorah.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kuah Asam Labuan Bajo',
        'description': 'Sup ikan kerapu/kakap kuah kuning bening asam segar berpadu belimbing wuluh, serai, daun kemangi, dan tomat muda.',
        'price_range': 'Rp45.000 - Rp80.000',
        'location': 'Kampung Ujung Kuliner Labuan Bajo',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manggaraibaratkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kolo (Nasi Bakar Bambu Khas Manggarai)',
        'description': 'Beras berempah gurih santan yang dimasak di dalam bilah bambu lalu dibakar di atas bara api kayu bakar harum.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Labuan Bajo, Flores Barat',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Cumi Saus Tiram Kampung Ujung',
        'description': 'Cumi segar empuk hasil tangkapan nelayan perairan Komodo yang dimasak saus tiram gurih manis di tepi dermaga marina.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Pusat Kuliner Malam Kampung Ujung',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 24. Desa Adat Wae Rebo
  DestinationDetailEntry(
    id: 24,
    shortDescription: 'Desa adat terpencil di atas awan lembah Manggarai Flores dengan 7 rumah kerucut keramat Mbaru Niang berarsitektur unik.',
    attractions: [
      {
        'id': '1',
        'name': '7 Rumah Kerucut Adat Mbaru Niang',
        'description': 'Rumah adat berbentuk kerucut 5 tingkat beratap daun lontar yang kokoh berdiri simetris di tengah lembah pegunungan.',
        'image': 'https://images.unsplash.com/photo-1643785879507-11a0c02205da?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya UNESCO',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Upacara Penyambutan Adat Waelu',
        'description': 'Ritual doa permohonan izin dan keselamatan oleh tetua adat di rumah utama (Mbaru Gendang) bagi setiap tamu yang datang.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Tradisi Adat',
        'estimated_cost': 50000,
        'source': 'https://manggaraikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Trekking Hutan Hujan Tropis Denge - Wae Rebo',
        'description': 'Jalur pendakian alami menyusuri sungai jernih, air terjun tersembunyi, dan kicauan burung endemik Flores.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Trekking Hutan Tropis',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Mbaru Niang Homestay Wae Rebo',
        'type': 'Traditional Lodge',
        'location': 'Desa Adat Wae Rebo, Manggarai, Flores',
        'price_range': 'Rp350.000 - Rp500.000 / orang (termasuk makan)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1643785879507-11a0c02205da?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Wae Rebo Lodge Dintor',
        'type': 'Lodge',
        'location': 'Desa Dintor, Satar Mese Barat, Manggarai',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manggaraikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Spring Hill Hotel Ruteng',
        'type': 'Hotel',
        'location': 'Ruteng, Manggarai, Flores',
        'price_range': 'Rp450.000 - Rp800.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manggaraikab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Kopi Flores Mangruva Wae Rebo',
        'description': 'Kopi arabika organik petik merah yang disangrai manual di tungku tanah liat kayu bakar warga adat.',
        'price_range': 'Rp15.000 - Rp35.000',
        'location': 'Mbaru Niang Wae Rebo',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manggaraikab.go.id/',
      },
      {
        'id': '2',
        'name': 'Nasi Jagung Gurih & Daun Labu Santan',
        'description': 'Makanan pokok tradisional paduan beras dan tumbukan jagung disajikan bersama oseng pucuk daun labu bumbu rempah.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Wae Rebo Adat Village',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Ayam Panggang Bumbu Serani Flores',
        'description': 'Ayam kampung bakar sederhana dengan bumbu garam, perasan jeruk nipis, serai, dan cabai rawit ulek pedas segar.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Denge & Wae Rebo',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manggaraikab.go.id/',
      },
    ],
  ),

  // 25. Danau Tiga Warna Kelimutu
  DestinationDetailEntry(
    id: 25,
    shortDescription: 'Gunung berapi di Flores dengan keajaiban 3 danau kawah kawah kramat yang warna airnya terus berubah secara misterius.',
    attractions: [
      {
        'id': '1',
        'name': 'Sunrise Puncak Titik Pandang Kelimutu',
        'description': 'Puncak tugu inspirasi di ketinggian 1.639 mdpl untuk menyaksikan matahari terbit berlatar 3 kawah berbeda warna.',
        'image': 'https://images.unsplash.com/photo-1654862048364-72d809f46a76?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Kawah Magis',
        'estimated_cost': 50000,
        'source': 'http://kelimutu.id/',
      },
      {
        'id': '2',
        'name': 'Tiwu Ata Polo & Tiwu Nuwa Muri Koo Fai',
        'description': 'Danau kembar berdinding tebing batu curam yang airnya berwarna merah tua/cokelat dan toska kehijauan berkilau.',
        'image': 'https://images.unsplash.com/photo-1719556346386-4300480b7403?q=80&w=800&auto=format&fit=crop',
        'category': 'Fenomena Geologi Langka',
        'estimated_cost': 0,
        'source': 'http://kelimutu.id/',
      },
      {
        'id': '3',
        'name': 'Desa Adat Moni & Air Terjun Murundao',
        'description': 'Desa gerbang Kelimutu dengan rumah adat tenun ikat tradisional suku Lio dan air terjun alami berair sejuk.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Budaya & Alam',
        'estimated_cost': 15000,
        'source': 'https://endekab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Kelimutu Crater Lakes Eco Lodge',
        'type': 'Eco-Lodge',
        'location': 'Desa Koanara, Moni, Ende, Flores',
        'price_range': 'Rp850.000 - Rp1.600.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ecolodgesindonesia.com/',
      },
      {
        'id': '2',
        'name': 'Grand Wisata Hotel Ende',
        'type': 'Hotel',
        'location': 'Jl. Kelimutu No.32, Ende, Flores',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://endekab.go.id/',
      },
      {
        'id': '3',
        'name': 'Moni Guesthouse & Cafe',
        'type': 'Guesthouse',
        'location': 'Jl. Trans Flores, Moni, Ende',
        'price_range': 'Rp200.000 - Rp380.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'http://kelimutu.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Uwi Ai Ndota (Singkong Parut Khas Ende)',
        'description': 'Olahan singkong parut khas suku Lio yang dikukus matang disajikan dengan suwiran ikan asin dan sambal lu’at pedas.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Moni & Kota Ende',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://endekab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kopi Arabika Moni Kelimutu',
        'description': 'Kopi arabika dataran tinggi beraroma rempah manis dengan keasaman seimbang hasil kebun lereng Kelimutu.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Kedai Kopi Moni',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Se’i Sapi Sambal Lu’at Khas Flores',
        'description': 'Daging sapi asap empuk aroma kayu kosambi disajikan dengan sambal perasan jeruk nipis dan daun sapan pedas segar.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Resto Ende & Moni',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),
];
