// ignore_for_file: lines_longer_than_80_chars
import 'destination_detail_entry.dart';

/// 3. Wilayah Sumatra (ID 26-33) & Kalimantan (ID 34-38)
final List<DestinationDetailEntry> sumatraKalimantanDetails = [
  // 26. Danau Toba & Pulau Samosir
  DestinationDetailEntry(
    id: 26,
    shortDescription: 'Danau vulkanik kaldera terbesar di dunia dengan Pulau Samosir di tengahnya, kaya akan warisan budaya Batak Toba.',
    attractions: [
      {
        'id': '1',
        'name': 'Desa Adat Tomok & Makam Raja Sidabutar',
        'description': 'Melihat rumah adat Batak Bolon bertanduk kerbau, makam batu monolitik raja, dan pertunjukan patung Sigale-gale.',
        'image': 'https://images.unsplash.com/photo-1657728401984-6d65350a4944?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Batak',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Bukit Holbung & Air Terjun Sipiso-Piso',
        'description': 'Bukit savana hijau berjuluk Bukit Teletubbies menghadap perairan biru Toba serta air terjun terjun bebas setinggi 120m.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Kaldera',
        'estimated_cost': 15000,
        'source': 'https://tobakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Batu Persidangan Huta Siallagan',
        'description': 'Situs kursi dan meja batu purba berusia ratusan tahun tempat pengadilan adat raja Batak tempo dulu.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Sejarah',
        'estimated_cost': 15000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Marianna Resort & Convention Toba',
        'type': 'Luxury Resort',
        'location': 'Tuktuk Siadong, Samosir',
        'price_range': 'Rp1.800.000 - Rp4.200.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://mariannaresort.com/',
      },
      {
        'id': '2',
        'name': 'Tabo Cottages Samosir',
        'type': 'Cottage',
        'location': 'Jl. Lingkar Tuktuk, Simanindo, Samosir',
        'price_range': 'Rp550.000 - Rp1.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://tabocottages.com/',
      },
      {
        'id': '3',
        'name': 'Toledo Inn Tuktuk Samosir',
        'type': 'Hotel',
        'location': 'Tuktuk Siadong, Pulau Samosir',
        'price_range': 'Rp350.000 - Rp750.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://samosirkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Mas Arsik Bumbu Andaliman',
        'description': 'Ikan mas segar danau dimasak bumbu kuning andaliman getir sedap, asam gelugur, lokio, dan kecombrang wangi.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Tuktuk & Balige, Danau Toba',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://tobakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Naniura (Sashimi Khas Batak)',
        'description': 'Olahan ikan mas mentah segar yang dimatangkan murni secara alami dengan perasan asam jungga dan rempah andaliman.',
        'price_range': 'Rp40.000 - Rp70.000',
        'location': 'Resto Tradisional Batak Toba',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kopi Lintong & Tipat Gomak Toba',
        'description': 'Mie lidi tebal berkuah santan andaliman gurih pedas hangat dipadukan secangkir kopi arabika Lintong nikmat.',
        'price_range': 'Rp15.000 - Rp30.000',
        'location': 'Kedai Balige & Parapat',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumutprov.go.id/',
      },
    ],
  ),

  // 27. Pulau Weh (Sabang)
  DestinationDetailEntry(
    id: 27,
    shortDescription: 'Titik Nol Kilometer paling barat Indonesia dengan surga terumbu karang bawah laut, pantai Iboih, dan Pulau Rubiah.',
    attractions: [
      {
        'id': '1',
        'name': 'Snorkeling & Diving Taman Laut Pulau Rubiah',
        'description': 'Taman laut lindung seluas 2.600 hektar berair sebening akuarium dengan aneka karang kipas dan ikan kakatua.',
        'image': 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 150000,
        'source': 'https://disbudpar.acehprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Monumen Tugu Nol Kilometer Indonesia',
        'description': 'Tugu penanda geografis ujung barat Nusantara di pucuk tebing hutan tropis menghadap megahnya Samudra Hindia.',
        'image': 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?q=80&w=800&auto=format&fit=crop',
        'category': 'Ikon Geografis Nasional',
        'estimated_cost': 10000,
        'source': 'https://sabangkota.go.id/',
      },
      {
        'id': '3',
        'name': 'Pantai Sumur Tiga & Iboih',
        'description': 'Pantai berpasir putih berkilau dengan deretan pohon kelapa tenang menghadap air laut bergradasi toska toska.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai & Santai',
        'estimated_cost': 10000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'The Pade Dive Resort Sabang',
        'type': 'Resort',
        'location': 'Jl. Balek Gunung, Iboih, Sukakarya, Sabang',
        'price_range': 'Rp1.100.000 - Rp2.400.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://thepade.com/',
      },
      {
        'id': '2',
        'name': 'Freddies Santai Sumurtiga',
        'type': 'Boutique Bungalow',
        'location': 'Jl. KH. Agus Salim, Sumur Tiga, Sabang',
        'price_range': 'Rp450.000 - Rp950.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disbudpar.acehprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Iboih Inn Resort & Restaurant',
        'type': 'Lodge',
        'location': 'Iboih Beach, Sukakarya, Sabang',
        'price_range': 'Rp350.000 - Rp700.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sabangkota.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Sate Gurita Sabang Saus Padang & Kacang',
        'description': 'Daging gurita segar empuk kenyal dibakar arang dan disiram kuah sate padang pedas gurih atau saus bumbu kacang.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Pusat Kuliner Wisata Sabang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sabangkota.go.id/',
      },
      {
        'id': '2',
        'name': 'Mie Jalak Sabang',
        'description': 'Mie kenyal berkuah kaldu ikan bening gurih segar dengan topping potongan daging ikan tongkol dan telur rebus.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Jl. Perdagangan, Kota Sabang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disbudpar.acehprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Kopi Sanger Ulee Kareng Khas Aceh',
        'description': 'Kopi tarik robusta saring pekat dengan sedikit susu kental manis berbusa lembut nikmat khas warung kopi Aceh.',
        'price_range': 'Rp10.000 - Rp18.000',
        'location': 'Kedai Kopi Sabang & Iboih',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 28. Ngarai Sianok & Jam Gadang
  DestinationDetailEntry(
    id: 28,
    shortDescription: 'Lembah ngarai patahan bumi spektakuler setinggi 100m berlatar Gunung Singgalang dan menara lonceng peninggalan Belanda Jam Gadang.',
    attractions: [
      {
        'id': '1',
        'name': 'Taman Panorama Ngarai Sianok & Lobang Jepang',
        'description': 'Gardu pandang tebing curam hijau dengan jaringan terowongan bunker militer Jepang sepanjang 1,4 km.',
        'image': 'https://images.unsplash.com/photo-1720033787459-0eb7ea2913d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Ngarai & Sejarah',
        'estimated_cost': 20000,
        'source': 'https://sumbarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Ikon Menara Jam Gadang',
        'description': 'Menara jam setinggi 26 meter peninggalan tahun 1926 dengan mesin mekanik langka serupa Big Ben London.',
        'image': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop',
        'category': 'Ikon Kota Bersejarah',
        'estimated_cost': 0,
        'source': 'https://bukittinggikota.go.id/',
      },
      {
        'id': '3',
        'name': 'Janjang 40 & Janjang Saribu',
        'description': 'Tangga seribu bertingkat yang menuruni ngarai nan asri menyerupai Tembok Besar Tiongkok versi Minangkabau.',
        'image': 'https://images.unsplash.com/photo-1653292952844-c1dd83d94967?q=80&w=800&auto=format&fit=crop',
        'category': 'Trekking & Spot Foto',
        'estimated_cost': 10000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'The Grand Rocky Hotel Bukittinggi',
        'type': 'Hotel',
        'location': 'Jl. Yos Sudarso No.29, Kayu Kubu, Bukittinggi',
        'price_range': 'Rp750.000 - Rp1.600.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rockyhotels.com/',
      },
      {
        'id': '2',
        'name': 'Novotel Bukittinggi',
        'type': 'Hotel',
        'location': 'Jl. Laras Datuk Bandaro, Benteng Pasar Atas',
        'price_range': 'Rp850.000 - Rp1.800.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://accor.com/',
      },
      {
        'id': '3',
        'name': 'Padi Resort Bukittinggi',
        'type': 'Resort',
        'location': 'Sianok Anambang, IV Koto, Agam',
        'price_range': 'Rp500.000 - Rp950.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumbarprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Nasi Kapau Los Lambuang Bukittinggi',
        'description': 'Nasi ramas khas Nagari Kapau dengan gulai tambusu, rendang daka-daka, itiak lado mudo, dan sambal hijau pedas gurih.',
        'price_range': 'Rp30.000 - Rp55.000',
        'location': 'Pasar Atas Los Lambuang, Bukittinggi',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bukittinggikota.go.id/',
      },
      {
        'id': '2',
        'name': 'Itiak Lado Mudo Ngarai',
        'description': 'Bebek muda empuk yang dimasak berlumur cabai hijau giling segar dan aneka rempah Minang gurih pekat.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Jl. Ngarai Binuang, Bukittinggi',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Pisang Kapik & Katupek Pitalah',
        'description': 'Pisang kepok bakar pipih bertabur parutan kelapa gula aren manis gurih serta ketupat gulai rebung khas Pitalah.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Kawasan Jam Gadang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 29. Taman Nasional Gunung Leuser
  DestinationDetailEntry(
    id: 29,
    shortDescription: 'Cagar biosfer hutan hujan tropis UNESCO di Bukit Barisan, habitat utama orangutan sumatra liar (Pongo abelii).',
    attractions: [
      {
        'id': '1',
        'name': 'Jungle Trekking Orangutan Bukit Lawang',
        'description': 'Menjelajahi kanopi hutan tropis primer dipterokarpa untuk melihat orangutan sumatra liar berayun bebas.',
        'image': 'https://images.unsplash.com/photo-1723153247780-02e191e1dd0c?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Satwa Liar',
        'estimated_cost': 250000,
        'source': 'https://gunungleuser.or.id/',
      },
      {
        'id': '2',
        'name': 'Jungle River Tubing Sungai Bahorok',
        'description': 'Sensasi mengarungi jeram sungai pegunungan berbatu jernih menggunakan ban pelampung raksasa berangkai.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan Sungai',
        'estimated_cost': 100000,
        'source': 'https://gunungleuser.or.id/',
      },
      {
        'id': '3',
        'name': 'Gua Kelelawar (Bat Cave) & Ekowisata Tangkahan',
        'description': 'Memandikan gajah konservasi di sungai dan menjelajahi formasi gua stalaktit alami di dalam hutan.',
        'image': 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=800&auto=format&fit=crop',
        'category': 'Ekowisata Konservasi',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Ecolodge Bukit Lawang',
        'type': 'Eco-Lodge',
        'location': 'Bukit Lawang, Bahorok, Langkat, Sumut',
        'price_range': 'Rp450.000 - Rp950.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ecolodgebukitlawang.com/',
      },
      {
        'id': '2',
        'name': 'Jungle Inn Bukit Lawang',
        'type': 'Lodge',
        'location': 'Tepi Sungai Bahorok, Bukit Lawang',
        'price_range': 'Rp350.000 - Rp750.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://gunungleuser.or.id/',
      },
      {
        'id': '3',
        'name': 'Tangkahan Inn & Bamboo River Lodge',
        'type': 'Eco-Lodge',
        'location': 'Batu Rongring, Namo Sialang, Tangkahan',
        'price_range': 'Rp300.000 - Rp600.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://langkatkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Gulai Ikan Jurung Khas Bahorok',
        'description': 'Ikan sungai khas hulu Leuser yang dimasak gulai asam pedas berpadu bunga kecombrang dan daun ruku-ruku.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Bukit Lawang, Langkat',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://langkatkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Nasi Lemak Bahorok Sambal Teri Medan',
        'description': 'Nasi gurih santan harum pandan dengan lauk telur balado, teri kacang renyah, serundeng, dan sambal terasi.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Warung Pagi Bukit Lawang',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumutprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Jus Buah Markisa Brastagi Segar',
        'description': 'Sari buah markisa segar asam manis khas perkebunan lereng pegunungan Sumatera Utara.',
        'price_range': 'Rp12.000 - Rp20.000',
        'location': 'Resto Jungle Inn Bukit Lawang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 30. Pantai Tanjung Tinggi
  DestinationDetailEntry(
    id: 30,
    shortDescription: 'Pantai ikonik Negeri Laskar Pelangi di Belitung dengan susunan batu granit purba raksasa dan pasir putih lembut.',
    attractions: [
      {
        'id': '1',
        'name': 'Labirin Batu Granit Purba Raksasa',
        'description': 'Menjelajahi celah lorong batu granit raksasa berusia ratusan juta tahun di bibir pantai berair toska tenang.',
        'image': 'https://images.unsplash.com/photo-1647783285870-8b318fd4c75e?q=80&w=800&auto=format&fit=crop',
        'category': 'Geosites UNESCO',
        'estimated_cost': 15000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Island Hopping Pulau Lengkuas & Mercusuar 1882',
        'description': 'Menaiki kapal nelayan ke Pulau Lengkuas dengan mercusuar peninggalan Belanda dan snorkeling terumbu karang.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 200000,
        'source': 'https://belitungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Danau Kaolin (Kulong Kaolin) Murai',
        'description': 'Danau bekas tambang kaolin dengan air biru cerah toska berpadu tebing daratan putih bersih mirip salju.',
        'image': 'https://images.unsplash.com/photo-1719556346386-4300480b7403?q=80&w=800&auto=format&fit=crop',
        'category': 'Spot Foto Geologis',
        'estimated_cost': 10000,
        'source': 'https://belitung.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Sheraton Belitung Resort',
        'type': 'Luxury Resort',
        'location': 'Jl. Pantai Penarikan Dusun Tanjung Kelayang, Sijuk',
        'price_range': 'Rp1.900.000 - Rp4.200.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://marriott.com/tjqsi',
      },
      {
        'id': '2',
        'name': 'Santika Premiere Beach Resort Belitung',
        'type': 'Resort',
        'location': 'Jl. Pantai Dusun Sinar Bulan, Sijuk, Belitung',
        'price_range': 'Rp950.000 - Rp1.900.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://santika.com/premiere-belitung/',
      },
      {
        'id': '3',
        'name': 'Lor In Belitung Hotel & Resort',
        'type': 'Hotel',
        'location': 'Jl. Tanjung Tinggi, Sijuk, Belitung',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://belitungkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Mie Belitung Atep Kaldu Udang',
        'description': 'Mie kuning kuah udang kental manis gurih dengan topping potongan tahu, kentang rebus, timun, emping melinjo, dan udang.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Tanjung Pandan, Belitung',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://belitungkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Gangan Ikan Ketarap Bumbu Kuning',
        'description': 'Sup ikan laut khas Belitung berkuah kuning kunyit asam segar nan pedas dengan potongan nanas muda renyah.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Resto Pantai Tanjung Tinggi & Kelayang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kopi Kong Djie Sejak 1943',
        'description': 'Kopi hitam legendaris yang diseduh dari ceret arang kuno dengan aroma wangi pekat khas Pulau Belitung.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Jl. Siburik, Tanjung Pandan',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://belitung.go.id/',
      },
    ],
  ),

  // 31. Lembah Harau
  DestinationDetailEntry(
    id: 31,
    shortDescription: 'Lembah ngarai granit tegak lurus setinggi 100-500m yang mengelilingi persawahan hijau asri di Kabupaten Lima Puluh Kota.',
    attractions: [
      {
        'id': '1',
        'name': 'Tebing Granit Raksasa & Panjat Tebing',
        'description': 'Dinding tebing batu granit terjal alami kelas dunia yang menjadi surga para pemanjat tebing internasional.',
        'image': 'https://images.unsplash.com/photo-1653292952844-c1dd83d94967?q=80&w=800&auto=format&fit=crop',
        'category': 'Geowisata & Olahraga Ekstrem',
        'estimated_cost': 20000,
        'source': 'https://limapuluhkotakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Air Terjun Sarasah Bunta & Aka Barayun',
        'description': 'Air terjun alami berair jernih dingin yang jatuh langsung dari pucuk tebing granit ke kolam pemandian alami.',
        'image': 'https://images.unsplash.com/photo-1720033787459-0eb7ea2913d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Air Terjun Alami',
        'estimated_cost': 15000,
        'source': 'https://sumbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Harau Sky & Kampung Eropa',
        'description': 'Wahana wisata rekreasi bertema miniatur desa Eropa berpadu hamparan sawah dan tebing alam megah.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Taman Rekreasi Tematik',
        'estimated_cost': 35000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Abdi Homestay Harau',
        'type': 'Eco-Homestay',
        'location': 'Lembah Harau, Tarantang, Lima Puluh Kota',
        'price_range': 'Rp250.000 - Rp500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://limapuluhkotakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Syafiq Homestay Lembah Harau',
        'type': 'Lodge',
        'location': 'Kawasan Sarasah Aka Barayun, Harau',
        'price_range': 'Rp300.000 - Rp650.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'The Balcone Hotel & Resort',
        'type': 'Resort',
        'location': 'Jl. Raya Bukittinggi - Payakumbuh KM.7',
        'price_range': 'Rp1.100.000 - Rp2.300.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://thebalconehotel.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Pongek Situjuah Payakumbuh',
        'description': 'Gulai nangka muda, rebung, dan daun singkong khas Situjuah yang dimasak santan kental gurih berempah pekat.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Situjuah & Lembah Harau',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://limapuluhkotakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Batiah & Gelamai Khas Payakumbuh',
        'description': 'Rengginang ketan berbutir renyah (batiah) serta dodol kenyal manis legit dari tepung ketan dan santan kelapa.',
        'price_range': 'Rp15.000 - Rp30.000',
        'location': 'Pusat Oleh-Oleh Payakumbuh',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sumbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Sate Danguang-Danguang Payakumbuh',
        'description': 'Sate daging sapi empuk dengan kuah kuning khas beraroma ketumbar kuat disajikan di atas ketupat daun kelapa.',
        'price_range': 'Rp25.000 - Rp40.000',
        'location': 'Payakumbuh & Harau',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 32. Taman Nasional Way Kambas
  DestinationDetailEntry(
    id: 32,
    shortDescription: 'Pusat konservasi dan suaka pelatihan gajah sumatra (Elephas maximus sumatranus) serta badak sumatra tertua di Indonesia.',
    attractions: [
      {
        'id': '1',
        'name': 'Pusat Konservasi Gajah (PKG) Karangsari',
        'description': 'Melihat aktivitas pelatihan, perawatan, dan berinteraksi dekat memandikan gajah sumatra di sungai alami.',
        'image': 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Gajah Liar',
        'estimated_cost': 50000,
        'source': 'http://waykambas.org/',
      },
      {
        'id': '2',
        'name': 'Safari Malam & Pengamatan Satwa Liar Plang Ijo',
        'description': 'Menjelajahi padang savana dan rawa untuk mengamati tapir, rusa sambar, dan burung mentok rimba langka.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Pengamatan Fauna',
        'estimated_cost': 100000,
        'source': 'http://waykambas.org/',
      },
      {
        'id': '3',
        'name': 'Susur Sungai Way Kanan dengan Perahu Motor',
        'description': 'Menyusuri aliran sungai berair tenang membelah hutan dataran rendah lebat berkanopi pohon trembesi raksasa.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Susur Sungai Alami',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Satwa Elephant Eco Lodge',
        'type': 'Eco-Lodge',
        'location': 'Jl. Labuhan Ratu IX, Way Kambas, Lampung Timur',
        'price_range': 'Rp650.000 - Rp1.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ecolodgesindonesia.com/',
      },
      {
        'id': '2',
        'name': 'Yoschi Guesthouse Way Kambas',
        'type': 'Guesthouse',
        'location': 'Labuhan Ratu, Lampung Timur',
        'price_range': 'Rp250.000 - Rp450.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'http://waykambas.org/',
      },
      {
        'id': '3',
        'name': 'Grand Mercure Lampung',
        'type': 'Hotel',
        'location': 'Jl. Raden Intan No.88, Bandar Lampung',
        'price_range': 'Rp1.200.000 - Rp2.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://accor.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Seruit Ikan Baung Khas Lampung',
        'description': 'Ikan air tawar sungai bakar yang diaduk bersama sambal terasi mentah, tempoyak durian fermentasi, dan mangga kuweni.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Lampung Timur & Bandar Lampung',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://lampungprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Gulai Taboh Ikan & Koro',
        'description': 'Gulai santan kental gurih khas Lampung berpadu kacang koro, rebung, dan potongan ikan laut asap beraroma harum.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Way Kambas & Sukadana',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kripik Pisang Cokelat Lumer Khas Lampung',
        'description': 'Keripik pisang kepok renyah tebal yang dibalut bubuk cokelat manis pekat legendaris khas Lampung.',
        'price_range': 'Rp15.000 - Rp30.000 / bungkus',
        'location': 'Pusat Oleh-Oleh Lampung',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://lampungprov.go.id/',
      },
    ],
  ),

  // 33. Benteng Marlborough & Pantai Panjang
  DestinationDetailEntry(
    id: 33,
    shortDescription: 'Benteng pertahanan kolonial Inggris terkuat di Asia peninggalan tahun 1714 menghadap Samudra Hindia di pesisir Bengkulu.',
    attractions: [
      {
        'id': '1',
        'name': 'Kompleks Benteng Fort Marlborough',
        'description': 'Benteng kokoh berbentuk kura-kura buatan British East India Company dengan meriam besi kuno dan ruang tahanan bersejarah.',
        'image': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Kolonial',
        'estimated_cost': 10000,
        'source': 'https://pariwisata.bengkuluprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Pantai Panjang Bengkulu Sunset Walk',
        'description': 'Garis pantai pasir putih landai sepanjang 7 km yang dinaungi deretan pohon cemara laut rindang berangin sejuk.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai Pesisir',
        'estimated_cost': 0,
        'source': 'https://bengkuluprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Rumah Pengasingan Bung Karno',
        'description': 'Situs cagar budaya kediaman Presiden Soekarno saat diasingkan pemerintah kolonial Belanda tahun 1938-1942.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Museum Sejarah Kemerdekaan',
        'estimated_cost': 10000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Mercure Bengkulu',
        'type': 'Hotel',
        'location': 'Jl. S. Parman No.27, Padang Jati, Bengkulu',
        'price_range': 'Rp750.000 - Rp1.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://accor.com/',
      },
      {
        'id': '2',
        'name': 'Grage Hotel Bengkulu',
        'type': 'Resort',
        'location': 'Jl. Nala No.142, Pantai Panjang, Bengkulu',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://gragehotelbengkulu.com/',
      },
      {
        'id': '3',
        'name': 'Santika Hotel Bengkulu',
        'type': 'Hotel',
        'location': 'Jl. Jend. Sudirman No.383, Pintu Batu',
        'price_range': 'Rp500.000 - Rp950.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://santika.com/bengkulu/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Pendap Bengkulu Ikan Laut Bumbu Kelapa',
        'description': 'Olahan ikan laut berbalut parutan kelapa kaya bumbu yang dibungkus berlapis-lapis daun talas lalu direbus berjam-jam.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Pasar Tradisional & Pantai Panjang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pariwisata.bengkuluprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Bagarr Hiu Khas Pesisir',
        'description': 'Masakan kuah gulai rempah pekat mirip rendang berbahan daging hiu cucut tanpa santan khas hidangan Bung Karno.',
        'price_range': 'Rp30.000 - Rp50.000',
        'location': 'Resto Khas Bengkulu',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bengkuluprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Kue Tat & Lempuk Durian Bengkulu',
        'description': 'Kue pai lembut berisi selai nanas khas raja-raja Bengkulu serta lempuk legit berbahan daging buah durian murni.',
        'price_range': 'Rp25.000 - Rp50.000',
        'location': 'Sentra Oleh-Oleh Jl. Soekarno Hatta',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 34. Taman Nasional Tanjung Puting
  DestinationDetailEntry(
    id: 34,
    shortDescription: 'Pusat konservasi orangutan liar terbesar di dunia di tengah belantara hutan hujan tropis Kalimantan dengan perahu klotok.',
    attractions: [
      {
        'id': '1',
        'name': 'Feeding Station Camp Leakey',
        'description': 'Stasiun riset orangutan tertua di dunia yang didirikan Dr. Biruté Galdikas untuk mengamati orangutan liar makan di panggung kayu.',
        'image': 'https://images.unsplash.com/photo-1630509930321-3e6e66c6cb04?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Orangutan',
        'estimated_cost': 200000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Jelajah Sungai Sekonyer Naik Perahu Klotok',
        'description': 'Sensasi berlayar dan bermalam di atas perahu kayu klotok melintasi sungai air hitam berhutan bakung dan kunang-kunang.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Susur Sungai Hutan Tropis',
        'estimated_cost': 800000, // include liveaboard klotok
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Stasiun Pondok Tanggui & Tanjung Harapan',
        'description': 'Tempat rehabilitasi orangutan muda dan mengamati bekantan hidung panjang bergelantungan di pucuk pohon nipah.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Fauna Liar Endemik',
        'estimated_cost': 50000,
        'source': 'https://kotawaringinbaratkab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Rimba Orangutan Eco Lodge',
        'type': 'Eco-Lodge',
        'location': 'Tepi Sungai Sekonyer, TN Tanjung Puting',
        'price_range': 'Rp1.600.000 - Rp3.200.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ecolodgesindonesia.com/',
      },
      {
        'id': '2',
        'name': 'Traditional Houseboat Klotok Liveaboard',
        'type': 'Liveaboard Boat',
        'location': 'Sungai Sekonyer, Kumai',
        'price_range': 'Rp1.200.000 - Rp2.500.000 / malam (all-in)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Swiss-Belinn Pangkalan Bun',
        'type': 'Hotel',
        'location': 'Jl. Ahmad Yani No.48, Pangkalan Bun',
        'price_range': 'Rp650.000 - Rp1.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://swiss-belhotel.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Soto Manggala Khas Pangkalan Bun',
        'description': 'Soto unik berkuah kaldu bening gurih berbahan dasar ketela pohon (singkong) empuk dengan potongan daging ayam.',
        'price_range': 'Rp15.000 - Rp28.000',
        'location': 'Pangkalan Bun & Kumai',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kotawaringinbaratkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Coto Menggala & Kerupuk Basah',
        'description': 'Olahan ikan belida/patin kenyal bumbu bawang putih khas pesisir Kumai disajikan hangat dengan sambal pedas asam.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Dermaga Kumai, Kotawaringin Barat',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Ikan Patin Bakar Bambu Rempah Dayak',
        'description': 'Ikan patin sungai segar dibumbui kunyit, serai, dan bawang hutan lalu dimasak dalam bambu di atas bara api klotok.',
        'price_range': 'Rp40.000 - Rp70.000',
        'location': 'Perahu Klotok Sungai Sekonyer',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 35. Kepulauan Derawan & Maratua
  DestinationDetailEntry(
    id: 35,
    shortDescription: 'Gugusan kepulauan tropis di Laut Sulawesi dengan danau ubur-ubur tak menyengat Kakaban dan surga pari manta Sangalaki.',
    attractions: [
      {
        'id': '1',
        'name': 'Berenang di Danau Ubur-Ubur Purba Kakaban',
        'description': 'Danau air asin purba terisolasi jutaan tahun yang dihuni 4 spesies ubur-ubur ramah tanpa sengat (stingless jellyfish).',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Keajaiban Bahari Dunia',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Manta Point & Penangkaran Penyu Pulau Sangalaki',
        'description': 'Snorkeling bersama kawanan pari manta raksasa (Manta birostris) dan melihat pelepasan anak penyu hijau ke laut.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 150000,
        'source': 'https://beraukab.go.id/',
      },
      {
        'id': '3',
        'name': 'Laguna Kehe Daing & Gua Halo Tabung Maratua',
        'description': 'Kolam gua air laut biru safir alami yang sangat jernih di bawah tebing karst karang Pulau Maratua.',
        'image': 'https://images.unsplash.com/photo-1682107222295-aebd076e2afb?q=80&w=800&auto=format&fit=crop',
        'category': 'Gua Laut Alami',
        'estimated_cost': 30000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Maratua Paradise Resort Overwater Villa',
        'type': 'Overwater Resort',
        'location': 'Pulau Maratua, Berau, Kalimantan Timur',
        'price_range': 'Rp2.200.000 - Rp4.800.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://maratuaparadise.com/',
      },
      {
        'id': '2',
        'name': 'Derawan Dive Lodge',
        'type': 'Resort',
        'location': 'Pesisir Pantai Derawan, Berau',
        'price_range': 'Rp1.100.000 - Rp2.400.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://derawandivelodge.com/',
      },
      {
        'id': '3',
        'name': 'Green Nirvana Maratua Resort',
        'type': 'Resort',
        'location': 'Teluk Harapan, Maratua, Berau',
        'price_range': 'Rp1.500.000 - Rp3.200.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://greennirvana.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Kima-Kima & Ikan Bakar Derawan',
        'description': 'Olahan kerang laut kima bumbu rempah kelapa asam segar serta ikan kakap merah bakar arang bumbu rica.',
        'price_range': 'Rp40.000 - Rp80.000',
        'location': 'Resto Pesisir Derawan & Maratua',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://beraukab.go.id/',
      },
      {
        'id': '2',
        'name': 'Tehe-Tehe Khas Suku Bajau',
        'description': 'Beras ketan gurih santan yang dimasak unik di dalam cangkang bulu babi berduri yang telah dibersihkan bersih.',
        'price_range': 'Rp15.000 - Rp25.000 / buah',
        'location': 'Perkampungan Suku Bajau Maratua',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Udang Galah Bakar Saus Asam Manis',
        'description': 'Udang galah air payau berukuran besar dengan daging kenyal manis dibakar saus mentega bawang gurih.',
        'price_range': 'Rp60.000 - Rp120.000',
        'location': 'Tanjung Batu & Derawan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 36. Danau Sentarum
  DestinationDetailEntry(
    id: 36,
    shortDescription: 'Taman nasional lahan basah danau musiman terluas di Asia Tenggara di jantung pedalaman hutan gambut Kapuas Hulu.',
    attractions: [
      {
        'id': '1',
        'name': 'Danau Musiman & Bukit Tekenang Viewpoint',
        'description': 'Puncak menara pandang Bukit Tekenang untuk menyaksikan panorama 80 danau yang saling terhubung di tengah hutan lebat.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Lahan Basah Ramsar',
        'estimated_cost': 30000,
        'source': 'http://betungkerihundanausentarum.menlhk.go.id/',
      },
      {
        'id': '2',
        'name': 'Habitat Ikan Arwana Super Red & Madu Hutan',
        'description': 'Melihat habitat asli ikan arwana merah liar dan proses pemanenan madu hutan organik lestari suku Dayak Iban.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Ekowisata Konservasi',
        'estimated_cost': 50000,
        'source': 'https://kapuashulukab.go.id/',
      },
      {
        'id': '3',
        'name': 'Rumah Betang Adat Dayak Iban Semangit',
        'description': 'Mengunjungi rumah panjang kayu ulin tradisional yang dihuni puluhan kepala keluarga dengan kearifan lokal menjaga hutan.',
        'image': 'https://images.unsplash.com/photo-1643785879507-11a0c02205da?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Dayak',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Resort Tekenang TN Danau Sentarum',
        'type': 'Eco-Resort',
        'location': 'Bukit Tekenang, Danau Sentarum, Kapuas Hulu',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'http://betungkerihundanausentarum.menlhk.go.id/',
      },
      {
        'id': '2',
        'name': 'Homestay Rumah Lanting Terapung',
        'type': 'Homestay',
        'location': 'Desa Lanjak & Leboyan, Danau Sentarum',
        'price_range': 'Rp200.000 - Rp400.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kapuashulukab.go.id/',
      },
      {
        'id': '3',
        'name': 'Grand Banana Hotel Putussibau',
        'type': 'Hotel',
        'location': 'Jl. Danau Sentarum, Putussibau',
        'price_range': 'Rp400.000 - Rp750.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kapuashulukab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Jelawat / Belida Bakar Bambu',
        'description': 'Ikan jelawat liar sungai Kapuas berlemak gurih dibakar dalam bilah bambu dengan bumbu serai dan cabai rawit Dayak.',
        'price_range': 'Rp45.000 - Rp85.000',
        'location': 'Lanjak & Danau Sentarum',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kapuashulukab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kerupuk Basah Ikan Toman Khas Kapuas Hulu',
        'description': 'Kuliner kenyal khas mirip pempek berbahan daging ikan toman murni disajikan hangat dengan sambal kacang pedas mantap.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Putussibau & Lanjak',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kalbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Madu Hutan Asli Danau Sentarum',
        'description': 'Madu liar murni lebah Apis dorsata beraroma nektar bunga pohon hutan gambut yang kaya khasiat stamina alami.',
        'price_range': 'Rp50.000 - Rp100.000 / botol',
        'location': 'Koperasi Madu Sentarum',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 37. Pasar Terapung Lok Baintan
  DestinationDetailEntry(
    id: 37,
    shortDescription: 'Pasar tradisional di atas perahu jukung di Sungai Martapura peninggalan Kesultanan Banjar yang masih menerapkan tradisi barter.',
    attractions: [
      {
        'id': '1',
        'name': 'Aktivitas Perahu Jukung Acil-Acil Banjar',
        'description': 'Menyaksikan ratusan ibu pedagang berperahu jukung kayu mengenakan topi caping lebar (tanggui) bertransaksi hasil bumi.',
        'image': 'https://images.unsplash.com/photo-1761789672627-c916c8464412?q=80&w=800&auto=format&fit=crop',
        'category': 'Tradisi Budaya Sungai',
        'estimated_cost': 50000, // sewa perahu klotok
        'source': 'https://dispar.kalselprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Tradisi Barter Kuno (Bapanduk)',
        'description': 'Melihat keunikan transaksi tukar menukar sayur, buah lokal, dan beras antar perahu tanpa uang tunai.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Kearifan Lokal',
        'estimated_cost': 0,
        'source': 'https://banjarkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Wisata Rumah Lanting & Pesisir Sungai Martapura',
        'description': 'Menyusuri permukiman rumah terapung kayu ulin di tepian sungai sambil menikmati sarapan soto di atas air.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Arsitektur Sungai',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Swiss-Belhotel Borneo Banjarmasin',
        'type': 'Hotel',
        'location': 'Jl. Pangeran Antasari No.86A, Banjarmasin',
        'price_range': 'Rp650.000 - Rp1.300.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://swiss-belhotel.com/',
      },
      {
        'id': '2',
        'name': 'Favehotel Ahmad Yani Banjarmasin',
        'type': 'Hotel',
        'location': 'Jl. Ahmad Yani KM 2.5 No.35, Banjarmasin',
        'price_range': 'Rp450.000 - Rp800.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://archipelagointernational.com/',
      },
      {
        'id': '3',
        'name': 'Rattan Inn Hotel Banjarmasin',
        'type': 'Resort Hotel',
        'location': 'Jl. A. Yani Km. 5,7, Banjarmasin',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rattan-inn.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Soto Banjar Limau Kuit & Ketupat',
        'description': 'Soto ayam berkaldu rempah kayu manis, cengkeh, dan kapulaga harum disajikan dengan perkedel singkong dan limau kuit.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Perahu Terapung Lok Baintan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.kalselprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Kue Wadai 41 Tradisional Banjar',
        'description': 'Koleksi aneka kue manis legit khas Banjar seperti bingka kentang, amparan tatak pisang, dan sari pengantin.',
        'price_range': 'Rp10.000 - Rp25.000',
        'location': 'Pasar Terapung & Pasar Wadai',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banjarkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Ikan Patin Bakar Bumbu Asam Manis Banjar',
        'description': 'Ikan patin sungai segar bakar arang disajikan dengan sambal terasi asam mangga kasturi wangi pedas.',
        'price_range': 'Rp30.000 - Rp55.000',
        'location': 'Warung Tepi Sungai Martapura',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 38. Bukit Kelam Sintang
  DestinationDetailEntry(
    id: 38,
    shortDescription: 'Batu monolit raksasa tertinggi kedua di dunia berketinggian 1.002 mdpl yang diselimuti tanaman kantong semar endemik langka.',
    attractions: [
      {
        'id': '1',
        'name': 'Via Ferrata Panjat Tebing Monolit Batu Kelam',
        'description': 'Jalur tangga besi via ferrata di dinding batu monolit vertikal tertinggi di Indonesia dengan adrenalin tinggi.',
        'image': 'https://images.unsplash.com/photo-1762787862952-d22aeb901f1e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panjat Tebing Ekstrem',
        'estimated_cost': 250000,
        'source': 'https://bksdakalbar.menlhk.go.id/',
      },
      {
        'id': '2',
        'name': 'Konservasi Kantong Semar Raksasa (Nepenthes clipeata)',
        'description': 'Melihat spesies tumbuhan karnivora pemakan serangga endemik yang hanya tumbuh liar di tebing terjal Bukit Kelam.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Flora Endemik Langka',
        'estimated_cost': 20000,
        'source': 'https://bksdakalbar.menlhk.go.id/',
      },
      {
        'id': '3',
        'name': 'Air Terjun Riam Berasap & Danau Sebedang',
        'description': 'Air terjun alami berhawa sejuk di kaki bukit batu dengan kolam pemandian alami hutan hujan Kalimantan.',
        'image': 'https://images.unsplash.com/photo-1653292952844-c1dd83d94967?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Air Terjun',
        'estimated_cost': 15000,
        'source': 'https://sintangkab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'My Home Hotel Sintang',
        'type': 'Hotel',
        'location': 'Jl. Lintas Melawi, Komplek My Home, Sintang',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sintangkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Hotel Bagoes Sintang',
        'type': 'Hotel',
        'location': 'Jl. Ahmad Yani No.39, Sintang, Kalbar',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kalbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Kelam Eco Lodge & Guesthouse',
        'type': 'Eco-Lodge',
        'location': 'Kaki Bukit Kelam, Kebong, Kelam Permai',
        'price_range': 'Rp200.000 - Rp380.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bksdakalbar.menlhk.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Pekasam Ikan Senggang Sintang',
        'description': 'Ikan air tawar sungai yang difermentasi dengan beras sangrai dan garam lalu dimasak tumis cabai bawang gurih asam.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Resto Khas Dayak Sintang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sintangkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Mie Kepiting Khas Sintang',
        'description': 'Mie kenyal olahan telur bebek disajikan dengan daging kepiting sungai manis, pangsit renyah, dan bakso ikan.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Jl. MT Haryono, Sintang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kalbarprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Lemang Pulut Bakar Bambu Sintang',
        'description': 'Ketan putih pulen gurih bersantan yang dipanggang dalam tabung bambu beralas daun pisang muda beraroma harum.',
        'price_range': 'Rp15.000 - Rp30.000 / batang',
        'location': 'Kios Kaki Bukit Kelam',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),
];
