// ignore_for_file: lines_longer_than_80_chars
import 'destination_detail_entry.dart';

/// 4. Wilayah Sulawesi (ID 39-45) & Maluku/Papua (ID 46-50)
final List<DestinationDetailEntry> sulawesiMalukuPapuaDetails = [
  // 39. Tana Toraja (Kete Kesu)
  DestinationDetailEntry(
    id: 39,
    shortDescription: 'Pusat kebudayaan megalitik suku Toraja dengan rumah adat Tongkonan beratap perahu dan kuburan tebing batu purba.',
    attractions: [
      {
        'id': '1',
        'name': 'Desa Adat Kete Kesu & Lumbung Padi Alang',
        'description': 'Perkampungan adat tertua dengan deretan rumah Tongkonan berukir motif geometris dan deretan tanduk kerbau pusaka.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Megalitik',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Kuburan Tebing Batu Londa & Patung Tau-Tau',
        'description': 'Gua pemakaman kuno di tebing karst batu kapur terjal yang dijaga patung kayu tiruan jenazah bangsawan (Tau-Tau).',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Pemakaman Kuno',
        'estimated_cost': 25000,
        'source': 'https://torajautarakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Negeri di Atas Awan Lolai',
        'description': 'Puncak bukit panorama di ketinggian 1.300 mdpl untuk menyaksikan hamparan samudera awan putih berlatar pegunungan hijau.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam Pegunungan',
        'estimated_cost': 15000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Toraja Heritage Hotel',
        'type': 'Resort',
        'location': 'Jl. Kete Kesu, Rantepao, Toraja Utara',
        'price_range': 'Rp1.100.000 - Rp2.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://torajaheritage.com/',
      },
      {
        'id': '2',
        'name': 'Toraja Misiliana Hotel',
        'type': 'Hotel',
        'location': 'Jl. Pongtiku No.27, Rantepao, Toraja Utara',
        'price_range': 'Rp750.000 - Rp1.600.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://torajamisiliana.com/',
      },
      {
        'id': '3',
        'name': 'Luta Resort Toraja',
        'type': 'Boutique Hotel',
        'location': 'Jl. Dr. Ratulangi No.26, Rantepao',
        'price_range': 'Rp500.000 - Rp950.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://torajautarakab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Pa’piong Daging Bumbu Mayana',
        'description': 'Daging sapi/ayam dibumbui daun mayana, serai, cabai katokkon, dan jahe lalu dipanggang matang dalam tabung bambu.',
        'price_range': 'Rp45.000 - Rp85.000',
        'location': 'Rantepao & Kete Kesu',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://torajautarakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kopi Arabika Toraja Sapan Single Origin',
        'description': 'Kopi arabika kelas dunia hasil perkebunan dataran tinggi Sapan dengan aroma floral herbal dan keasaman seimbang.',
        'price_range': 'Rp15.000 - Rp35.000',
        'location': 'Kedai Kopi Rantepao',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Pantollo Lendong Bumbu Pangi',
        'description': 'Olahan belut sawah khas Toraja yang dimasak kuah hitam pekat berbumbu kluwek pangi dan cabai katokkon pedas membakar.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Resto Tradisional Rantepao',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sulselprov.go.id/',
      },
    ],
  ),

  // 40. Taman Nasional Bunaken
  DestinationDetailEntry(
    id: 40,
    shortDescription: 'Taman laut dunia di Teluk Manado dengan dinding karang vertikal bawah laut (underwater vertical wall) sedalam 25-50 meter.',
    attractions: [
      {
        'id': '1',
        'name': 'Diving di Bunaken Coral Wall',
        'description': 'Menyelam di tebing karang vertikal spektakuler dengan jarak pandang 30 meter dihuni 390 spesies karang dan penyu raksasa.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Diving Dunia',
        'estimated_cost': 350000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Snorkeling Lekuan I, II & III',
        'description': 'Spot snorkeling favorit perairan dangkal jernih dengan kawanan ikan nemo badut dan kura-kura sisik ramah.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Snorkeling Terumbu Karang',
        'estimated_cost': 150000,
        'source': 'https://manadokota.go.id/',
      },
      {
        'id': '3',
        'name': 'Wisata Kapal Kaca Katamaran & Pulau Siladen',
        'description': 'Melihat keindahan taman laut bawah air tanpa basah melalui lantai kaca perahu katamaran di perairan Siladen.',
        'image': 'https://images.unsplash.com/photo-1682107222295-aebd076e2afb?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari Keluarga',
        'estimated_cost': 200000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Siladen Resort & Spa',
        'type': 'Luxury Eco-Resort',
        'location': 'Pulau Siladen, TN Bunaken, Manado',
        'price_range': 'Rp3.500.000 - Rp7.200.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://siladen.com/',
      },
      {
        'id': '2',
        'name': 'Bunaken Oasis Dive Resort and Spa',
        'type': 'Dive Resort',
        'location': 'Liang Beach, Pulau Bunaken, Manado',
        'price_range': 'Rp2.800.000 - Rp5.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bunakenoasis.com/',
      },
      {
        'id': '3',
        'name': 'Novotel Manado Golf Resort & Convention Center',
        'type': 'Hotel Resort',
        'location': 'Jl. AA Maramis Kayuwatu Kairagi II, Manado',
        'price_range': 'Rp850.000 - Rp1.700.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://accor.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Tinutuan (Bubur Manado) Ikan Asin & Sambal Roa',
        'description': 'Bubur jagung labu kuning kaya sayuran kangkung, kemangi, bayam, disajikan dengan ikan asin renyah dan sambal roa pedas.',
        'price_range': 'Rp15.000 - Rp28.000',
        'location': 'Jl. Wakeke, Kawasan Kuliner Manado',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://manadokota.go.id/',
      },
      {
        'id': '2',
        'name': 'Ikan Cakalang Fufu Saus Rica-Rica',
        'description': 'Ikan cakalang laut segar yang diasapi di atas bilah bambu lalu disiram bumbu rica-rica cabai merah ulek pedas gurih.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Resto Pesisir Manado & Bunaken',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sulutprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Klappertaart Asli Manado',
        'description': 'Dessert lembut manis gurih peninggalan Belanda berbahan kelapa muda, susu, kenari panggang, dan taburan kismis kayu manis.',
        'price_range': 'Rp20.000 - Rp45.000',
        'location': 'Toko Oleh-Oleh Manado',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 41. Kepulauan Togean
  DestinationDetailEntry(
    id: 41,
    shortDescription: 'Gugusan pulau surga terpencil di Teluk Tomini dengan danau ubur-ubur Mariona, karang atol purba, dan desa suku Bajo terapung.',
    attractions: [
      {
        'id': '1',
        'name': 'Danau Ubur-Ubur Mariona Togean',
        'description': 'Danau air laut terisolasi yang dipenuhi ribuan ubur-ubur tanpa sengat transparan kemerahan yang aman disentuh.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Keajaiban Bahari',
        'estimated_cost': 30000,
        'source': 'https://togeannationalpark.id/',
      },
      {
        'id': '2',
        'name': 'Desa Terapung Suku Bajo Kabalutan',
        'description': 'Perkampungan rumah panggung kayu di atas terumbu karang dangkal tempat tinggal para pengelana laut ulung Suku Bajo.',
        'image': 'https://images.unsplash.com/photo-1682107222295-aebd076e2afb?q=80&w=800&auto=format&fit=crop',
        'category': 'Budaya Bahari Suku Bajo',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Reef 1 to 5 & Pantai Karina',
        'description': 'Rangkaian titik penyelaman atol karang terluas di Indonesia berair sangat tenang sebening kristal.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Spot Snorkeling & Atol Karang',
        'estimated_cost': 150000,
        'source': 'https://togeannationalpark.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Sanctum Una Una Eco Dive Resort',
        'type': 'Eco-Resort',
        'location': 'Pulau Una Una, Kepulauan Togean',
        'price_range': 'Rp950.000 - Rp1.900.000 / malam (full board)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sanctum-unauna.com/',
      },
      {
        'id': '2',
        'name': 'Kadidiri Paradise Resort',
        'type': 'Resort',
        'location': 'Pulau Kadidiri, TN Kepulauan Togean',
        'price_range': 'Rp650.000 - Rp1.300.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://togeannationalpark.id/',
      },
      {
        'id': '3',
        'name': 'Harmony Bay Resort Togean',
        'type': 'Bungalow',
        'location': 'Pulau Batudaka, Kepulauan Togean',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kuah Asam Pedas Suku Bajo',
        'description': 'Ikan kakap/kerapu laut segar tangkapan tombak suku Bajo dimasak kuah bening asam jeruk nipis, kunyit, dan cabai rawit.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Resort Togean & Desa Kabalutan',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://togeannationalpark.id/',
      },
      {
        'id': '2',
        'name': 'Kasami (Kasoami Ubi Parut Khas Pesisir)',
        'description': 'Makanan pokok pengganti nasi berbahan parutan singkong fermentasi yang dikukus dalam cetakan kerucut daun kelapa.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Waketuma & Kadidiri',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Cumi & Gurita Bakar Madu Bakau',
        'description': 'Gurita segar empuk yang dipanggang dengan olesan madu hutan bakau dan sambal terasi dabu-dabu iris segar.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Pulau Kadidiri',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 42. Taman Nasional Wakatobi
  DestinationDetailEntry(
    id: 42,
    shortDescription: 'Cagar Biosfer Bumi UNESCO di jantung segitiga terumbu karang dunia (Coral Triangle) dengan 750 spesies koral karang hidup.',
    attractions: [
      {
        'id': '1',
        'name': 'Diving Spot Roma & House Reef Tomia',
        'description': 'Menyelam di antara taman koral meja raksasa, kawanan ikan barracuda, dan kuda laut kerdil (pygmy seahorse).',
        'image': 'https://images.unsplash.com/photo-1715899735604-10c58aabd39f?q=80&w=800&auto=format&fit=crop',
        'category': 'Diving Karang Terkaya Dunia',
        'estimated_cost': 400000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Puncak Khayangan Tomia Sunset',
        'description': 'Bukit savana berundak hijau di Pulau Tomia dengan panorama matahari terbenam memukau menghadap laut Wakatobi.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Savana Pesisir',
        'estimated_cost': 15000,
        'source': 'https://wakatobikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Desa Terapung Mola Suku Bajo Wangi-Wangi',
        'description': 'Melihat kehidupan anak-anak suku Bajo yang berenang bebas di bawah kolong rumah panggung terapung di tengah laut.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Kearifan Lokal Maritim',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Wakatobi Dive Resort Onong Resort',
        'type': 'Luxury Dive Resort',
        'location': 'Pulau Tolandono / Tomia, Wakatobi',
        'price_range': 'Rp4.500.000 - Rp9.500.000 / malam (all-inclusive)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wakatobi.com/',
      },
      {
        'id': '2',
        'name': 'Patuno Resort Wakatobi',
        'type': 'Resort',
        'location': 'Jl. Raya Patuno No.1, Wangi-Wangi, Wakatobi',
        'price_range': 'Rp850.000 - Rp1.800.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://patunoresort.com/',
      },
      {
        'id': '3',
        'name': 'Hoga Island Dive Resort',
        'type': 'Eco-Lodge',
        'location': 'Pulau Hoga, Kaledupa, Wakatobi',
        'price_range': 'Rp450.000 - Rp900.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wakatobikab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Kasuami & Ikan Parende Wakatobi',
        'description': 'Kue ubi kerucut gurih dinikmati bersama sup ikan kakap merah kuah kuning asam segar bercita rasa belimbing wuluh.',
        'price_range': 'Rp30.000 - Rp55.000',
        'location': 'Wangi-Wangi & Tomia, Wakatobi',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wakatobikab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kukure (Bulu Babi Olahan Khas Bajo)',
        'description': 'Daging bulu babi laut segar dimasak bumbu kunyit kelapa parut sangrai manis gurih khas nelayan tradisional.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Desa Mola & Kaledupa',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Karu-Karu Ikan Cakalang Asap',
        'description': 'Suwiran daging ikan cakalang asap yang digoreng garing renyah dengan cabai merah pedas manis gurih.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Pasar Tradisional Wangi-Wangi',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sultraprov.go.id/',
      },
    ],
  ),

  // 43. KEK Likupang (Pantai Paal)
  DestinationDetailEntry(
    id: 43,
    shortDescription: 'Destinasi Pariwisata Super Prioritas di ujung utara Sulawesi dengan perbukitan hijau Larata dan pasir putih Pantai Paal & Pulisan.',
    attractions: [
      {
        'id': '1',
        'name': 'Pantai Paal Marinsow Pasir Putih',
        'description': 'Garis pantai pasir putih landai dengan gradasi warna air laut toska kebiruan jernih di Teluk Marinsow.',
        'image': 'https://images.unsplash.com/photo-1761530124592-0ea700a319cb?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai Pasir Putih',
        'estimated_cost': 15000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Bukit Savana Larata & Gua Pantai Pulisan',
        'description': 'Trekking bukit ilalang hijau berpemandangan laut lepas Sulawesi dan tebing batu berlubang di Pantai Pulisan.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Bukit Savana',
        'estimated_cost': 20000,
        'source': 'https://minut.go.id/',
      },
      {
        'id': '3',
        'name': 'Snorkeling & Diving Pulau Lihaga',
        'description': 'Pulau tak berpenghuni seluas 8 hektar berpasir putih selembut bedak dengan terumbu karang alami yang terjaga.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Pulau Wisata Bahari',
        'estimated_cost': 100000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Casabaio Paradise Resort Likupang',
        'type': 'Resort',
        'location': 'Desa Maen, Likupang Timur, Minahasa Utara',
        'price_range': 'Rp1.200.000 - Rp2.500.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://casabaioresort.com/',
      },
      {
        'id': '2',
        'name': 'Pulisan Jungle Beach Resort',
        'type': 'Eco-Lodge',
        'location': 'Pantai Pulisan, Likupang Timur',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://minut.go.id/',
      },
      {
        'id': '3',
        'name': 'Lihaga Beach Club Glamping',
        'type': 'Glamping',
        'location': 'Pulau Lihaga, Likupang',
        'price_range': 'Rp750.000 - Rp1.600.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Tinorangsak Ikan Tuna Likupang',
        'description': 'Potongan ikan tuna segar dimasak bumbu rempah cabai rawit hijau, jahe, kunyit, dan daun jeruk dalam bambu harum.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Likupang Timur & Manado',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://minut.go.id/',
      },
      {
        'id': '2',
        'name': 'Panada Ikan Cakalang Pedas Gurih',
        'description': 'Roti goreng empuk khas Minahasa berisi suwiran ikan cakalang berbumbu pampis pedas wangi daun kemangi.',
        'price_range': 'Rp5.000 - Rp10.000 / buah',
        'location': 'Kedai Pesisir Pantai Paal',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Bakar Ikan Baronang Saus Dabu-Dabu Lilang',
        'description': 'Ikan baronang laut bakar arang disajikan dengan siraman dabu-dabu tomat, cabai rawit merah, dan bawang merah iris segar.',
        'price_range': 'Rp45.000 - Rp80.000',
        'location': 'Resto Pantai Paal & Pulisan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sulutprov.go.id/',
      },
    ],
  ),

  // 44. Rammang-Rammang Karst
  DestinationDetailEntry(
    id: 44,
    shortDescription: 'Gugusan pegunungan karst menara terluas ketiga di dunia di Maros dengan susur sungai Pute bertebing purba.',
    attractions: [
      {
        'id': '1',
        'name': 'Susur Sungai Pute Naik Perahu Jolloro',
        'description': 'Berlayar menyusuri sungai tenang di antara celah tebing batu karst kapur raksasa dan deretan pohon nipah rindang.',
        'image': 'https://images.unsplash.com/photo-1776624906357-dad5ad7f8d42?q=80&w=800&auto=format&fit=crop',
        'category': 'Susur Sungai Karst',
        'estimated_cost': 75000,
        'source': 'https://disbudpar.sulselprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Kampung Berua di Tengah Dinding Karst',
        'description': 'Perkampungan tradisional asri yang terisolasi di dalam cekungan lembah sawah hijau berdinding tebing batu karst 360 derajat.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Desa Wisata Lembah Karst',
        'estimated_cost': 15000,
        'source': 'https://maroskab.go.id/',
      },
      {
        'id': '3',
        'name': 'Taman Batu Karst (Stone Park) & Gua Berlian',
        'description': 'Hamparan batuan kapur hitam alami berarsitektur unik hasil kikisan hujan dan angin selama ribuan tahun.',
        'image': 'https://images.unsplash.com/photo-1762787862952-d22aeb901f1e?q=80&w=800&auto=format&fit=crop',
        'category': 'Geopark UNESCO',
        'estimated_cost': 10000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Rammang-Rammang Eco Lodge',
        'type': 'Eco-Lodge',
        'location': 'Dermaga 1 Rammang-Rammang, Maros',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://maroskab.go.id/',
      },
      {
        'id': '2',
        'name': 'Grand Town Hotel Mandai Maros',
        'type': 'Hotel',
        'location': 'Jl. Poros Maros - Makassar KM 22',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://grandtownhotel.com/',
      },
      {
        'id': '3',
        'name': 'Claro Hotel Makassar (Dekat Akses Maros)',
        'type': 'Hotel',
        'location': 'Jl. A.P. Pettarani No.03, Makassar',
        'price_range': 'Rp850.000 - Rp1.700.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://claromakassar.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Coto Maros Bumbu Rempah Kacang',
        'description': 'Coto berkuah kaldu sapi kental kaya rempah ketumbar dan kacang tanah gurih disajikan dengan ketupat daun pandan.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Jl. Poros Maros & Rammang-Rammang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://maroskab.go.id/',
      },
      {
        'id': '2',
        'name': 'Roti Maros Selai Srikaya Tradisional',
        'description': 'Roti sobek bulat lembut hangat dengan isian selai srikaya telur gula aren yang manis legit beraroma harum.',
        'price_range': 'Rp15.000 - Rp25.000 / kotak',
        'location': 'Sentra Roti Maros Jl. Poros',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disbudpar.sulselprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Ikan Bandeng Bakar Tanpa Duri Maros',
        'description': 'Bandeng air payau bakar empuk tanpa duri dengan lumuran bumbu parape kecap bawang merah dan sambal dabu-dabu.',
        'price_range': 'Rp30.000 - Rp50.000',
        'location': 'Kawasan Wisata Kampung Berua',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 45. Pantai Tanjung Bira
  DestinationDetailEntry(
    id: 45,
    shortDescription: 'Pantai pasir putih selembut bedak tepung di Bulukumba, pusat pembuatan perahu layar tradisional Pinisi warisan UNESCO.',
    attractions: [
      {
        'id': '1',
        'name': 'Sentra Galangan Perahu Tradisional Pinisi Tanah Beru',
        'description': 'Menyaksikan langsung ketangkasan para maestro pembuat kapal layar Pinisi kayu raksasa legendaris tanpa paku besi.',
        'image': 'https://images.unsplash.com/photo-1671579877091-e720c1bfc668?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya UNESCO',
        'estimated_cost': 20000,
        'source': 'https://bulukumbakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Tebing Karst Apparalang & Snorkeling',
        'description': 'Tebing karang terjal berundak menjorok ke perairan laut toska transparan dengan spot lompat tebing (cliff jumping).',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Tebing & Snorkeling',
        'estimated_cost': 25000,
        'source': 'https://bulukumbakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Snorkeling & Diving Pulau Liukang Loe',
        'description': 'Berenang di penangkaran penyu hijau laut dan terumbu karang dangkal pulau pasir putih di seberang Tanjung Bira.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Amatoa Resort Tanjung Bira',
        'type': 'Boutique Cliff Resort',
        'location': 'Jl. Pasir Putih, Tanjung Bira, Bulukumba',
        'price_range': 'Rp1.400.000 - Rp2.900.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://amatoaresort.com/',
      },
      {
        'id': '2',
        'name': 'Same Resort Bira Beach',
        'type': 'Resort',
        'location': 'Jl. Pantai Tanjung Bira, Bonto Bahari',
        'price_range': 'Rp750.000 - Rp1.500.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sameresort.com/',
      },
      {
        'id': '3',
        'name': 'Cosmo Bungalows Bira',
        'type': 'Bungalow',
        'location': 'Pantai Bira, Bulukumba',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bulukumbakab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Bakar Parape & Sambal Dabu-Dabu Bira',
        'description': 'Ikan kakap/kanang bakar olesan saus manis pedas karamel bawang merah parape disajikan di pinggir pasir putih.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Pesisir Tanjung Bira',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bulukumbakab.go.id/',
      },
      {
        'id': '2',
        'name': 'Kapurung Ikan Khas Sulawesi Selatan',
        'description': 'Kuliner sagu kenyal berkuah sup ikan bumbu asam patikala (kecombrang) dengan sayur bayam, jantung pisang, dan jagung.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Warung Tradisional Bulukumba',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disbudpar.sulselprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Kue Uhu-Uhu & Barongko Pisang',
        'description': 'Kue tradisional manis gurih berbahan adonan pisang kepok halus, santan, telur, dan gula yang dikukus dalam daun pisang.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Sentra Kuliner Bira',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 46. Kepulauan Raja Ampat (Piaynemo)
  DestinationDetailEntry(
    id: 46,
    shortDescription: 'Mahakarya gugusan pulau karang karst (piaynemo) di laut toska zamrud dengan keanekaragaman hayati laut terkaya di muka bumi.',
    attractions: [
      {
        'id': '1',
        'name': 'Puncak Panorama Piaynemo (Little Wayag)',
        'description': 'Menaiki 320 anak tangga kayu menuju gardu pandang ikonik gugusan pulau-pulau karst kecil di atas laut zamrud.',
        'image': 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Karst Ikonik',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Telaga Bintang (Star Lagoon)',
        'description': 'Laguna alam air laut berbentuk bintang sempurna yang terbentuk alami di antara formasi tebing karang terjal.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Formasi Geologi Alami',
        'estimated_cost': 30000,
        'source': 'https://rajaampatkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Diving Spot Cape Kri & Manta Sandy',
        'description': 'Spot penyelaman pemegang rekor dunia 374 spesies ikan dalam satu kali dive dan stasiun pembersihan pari manta.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Diving Kelas Dunia',
        'estimated_cost': 450000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Misool Eco Resort Raja Ampat',
        'type': 'Ultra-Luxury Eco-Resort',
        'location': 'Pulau Batbitim, Misool Selatan, Raja Ampat',
        'price_range': 'Rp15.000.000 - Rp35.000.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://misool.info/',
      },
      {
        'id': '2',
        'name': 'Raja Ampat Biodiversity Nature Resort',
        'type': 'Eco-Resort',
        'location': 'Pantai Yenanas, Pulau Gam, Raja Ampat',
        'price_range': 'Rp2.800.000 - Rp5.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rajaampatbiodiversity.com/',
      },
      {
        'id': '3',
        'name': 'Piaynemo Homestay Overwater',
        'type': 'Overwater Homestay',
        'location': 'Kawasan Piaynemo, Kepulauan Fam, Raja Ampat',
        'price_range': 'Rp650.000 - Rp1.200.000 / malam (full board)',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rajaampatkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Papeda Kuah Kuning Ikan Tongkol / Kakap',
        'description': 'Bubur sagu kenyal khas Papua disiram kuah ikan bumbu kuning kunyit asam segar, daun kemangi, dan cabai rawit pedas.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Waisai & Homestay Piaynemo',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://rajaampatkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Ikan Bakar Batu Bumbu Manokwari',
        'description': 'Ikan tenggiri/kakap laut segar dipanggang dengan olesan sambal giling mentah cabai rawit kasar khas pesisir Papua.',
        'price_range': 'Rp45.000 - Rp85.000',
        'location': 'Pesisir Pulau Gam & Waisai',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Sate Ulat Sagu Gurih Karamel',
        'description': 'Kuliner tradisional kaya protein tinggi khas hutan sagu Papua yang dibakar kecap manis gurih bertekstur lembut lumer.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Desa Wisata Sawinggrai',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 47. Kepulauan Banda Neira
  DestinationDetailEntry(
    id: 47,
    shortDescription: 'Pusat Kepulauan Rempah pala bersejarah dunia dengan Benteng Belgica abad ke-17 berlatar megahnya Gunung Api Banda.',
    attractions: [
      {
        'id': '1',
        'name': 'Benteng Belgica & Benteng Nassau',
        'description': 'Benteng pentagonal megah peninggalan VOC tahun 1611 di atas bukit dengan panorama 360 derajat teluk Banda Neira.',
        'image': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Benteng VOC',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Pendakian Gunung Api Banda (656 MDPL)',
        'description': 'Mendaki gunung api aktif di tengah laut melintasi bebatuan lava hitam dengan pemandangan karang bawah air jernih.',
        'image': 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=800&auto=format&fit=crop',
        'category': 'Pendakian Vulkanik',
        'estimated_cost': 50000,
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Snorkeling Lava Flow Pulau Gunung Api',
        'description': 'Taman terumbu karang hidup terindah dan tercepat tumbuh di dunia di atas aliran lava letusan tahun 1988.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Taman Karang Lava Alami',
        'estimated_cost': 150000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'The Maulana Hotel Banda Neira',
        'type': 'Historic Hotel',
        'location': 'Jl. Pelabuhan, Banda Neira, Maluku Tengah',
        'price_range': 'Rp650.000 - Rp1.400.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Cilu Bintang Estate',
        'type': 'Boutique Hotel',
        'location': 'Jl. Nusantara, Banda Neira',
        'price_range': 'Rp550.000 - Rp1.200.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://cilubintang.com/',
      },
      {
        'id': '3',
        'name': 'Banda Neira Dive Homestay',
        'type': 'Homestay',
        'location': 'Nusantara, Banda Neira, Maluku Tengah',
        'price_range': 'Rp250.000 - Rp450.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kuah Pala Banda Neira',
        'description': 'Kuliner legendaris rempah buah pala asli Banda berpadu daging ikan laut segar berkuah asam pedas hangat harum.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Resto Sejarah Banda Neira',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Halua Kenari & Selai Buah Pala',
        'description': 'Camilan manis renyah khas pulau rempah berbahan biji kenari sangrai dibalut gula aren karamel manis legit.',
        'price_range': 'Rp15.000 - Rp35.000',
        'location': 'Toko Oleh-Oleh Banda Neira',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Sambal Bakasang Ikan Cakalang',
        'description': 'Sambal khas Maluku berbahan dasar fermentasi telur ikan cakalang dengan cabai rawit pedas mantap dan perasan jeruk limau.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Warung Tradisional Nusantara',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
    ],
  ),

  // 48. Lembah Baliem
  DestinationDetailEntry(
    id: 48,
    shortDescription: 'Lembah dataran tinggi megah pegunungan Jayawijaya Papua yang dihuni suku asli Dani, Lani, dan Yali dengan tradisi mumi purba.',
    attractions: [
      {
        'id': '1',
        'name': 'Desa Adat Jiwika & Mumi Purba Kurulu',
        'description': 'Melihat mumi leluhur panglima perang suku Dani berusia 370 tahun yang diawetkan dengan asap alami di dalam honai.',
        'image': 'https://images.unsplash.com/photo-1683713601159-0b22f5116f88?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya Mumi Purba',
        'estimated_cost': 100000,
        'source': 'https://papua.go.id/',
      },
      {
        'id': '2',
        'name': 'Festival Budaya Lembah Baliem (FBLB)',
        'description': 'Perayaan tahunan kolosal atraksi perang-perangan tradisional antar suku lengkap dengan pakaian adat dan tarian perang.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Festival Budaya Dunia',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Gua Kotilola & Danau Habema (Danau di Atas Awan)',
        'description': 'Gua karst raksasa dengan stalaktit megah serta danau alami tertinggi di Indonesia berketinggian 3.300 mdpl berlatar Puncak Trikora.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam Pegunungan',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Baliem Valley Resort',
        'type': 'Eco-Resort',
        'location': 'Desa Sekan, Lembah Baliem, Wamena',
        'price_range': 'Rp1.800.000 - Rp3.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://baliem-valley-resort.com/',
      },
      {
        'id': '2',
        'name': 'Grand Baliem Hotel Wamena',
        'type': 'Hotel',
        'location': 'Jl. Trikora No.58, Wamena, Jayawijaya',
        'price_range': 'Rp750.000 - Rp1.500.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://papua.go.id/',
      },
      {
        'id': '3',
        'name': 'Honai Resort & Cultural Lodge',
        'type': 'Traditional Lodge',
        'location': 'Jiwika, Wamena, Jayawijaya',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Udang Selingkuh Wamena Saus Asam Manis',
        'description': 'Udang air tawar endemik Sungai Baliem bercapit besar seperti kepiting dengan daging super tebal, manis, dan kenyal.',
        'price_range': 'Rp75.000 - Rp150.000',
        'location': 'Resto Wamena & Lembah Baliem',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://papua.go.id/',
      },
      {
        'id': '2',
        'name': 'Ubi Jalar Manis (Hipere) Bakar Batu',
        'description': 'Ubi jalar manis kaya karbohidrat khas suku Dani yang dimasak dalam upacara tradisional bakar batu (barapen).',
        'price_range': 'Rp15.000 - Rp30.000',
        'location': 'Desa Adat Jiwika & Kurulu',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kopi Arabika Wamena Organik',
        'description': 'Kopi arabika pegunungan Jayawijaya yang ditanam organik tanpa pupuk kimia di ketinggian 1.800 mdpl beraroma earthy herbal.',
        'price_range': 'Rp20.000 - Rp40.000',
        'location': 'Kedai Kopi Wamena',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 49. Taman Nasional Teluk Cenderawasih
  DestinationDetailEntry(
    id: 49,
    shortDescription: 'Taman nasional laut terluas di Indonesia di Papua Barat Daya, surga berenang bersama hiu paus jinak (Rhincodon typus).',
    attractions: [
      {
        'id': '1',
        'name': 'Berenang Bersama Hiu Paus di Bagan Kwatisore',
        'description': 'Pengalaman langka seumur hidup berenang dan snorkeling bersama kawanan hiu paus raksasa jinak di samping bagan nelayan.',
        'image': 'https://images.unsplash.com/photo-1540202404-b2979d19ed37?q=80&w=800&auto=format&fit=crop',
        'category': 'Interaksi Satwa Laut Raksasa',
        'estimated_cost': 350000,
        'source': 'https://telukcenderawasih.org/',
      },
      {
        'id': '2',
        'name': 'Pulau Rumberpon & Pantai Pasir Panjang',
        'description': 'Garis pantai pasir putih sepanjang 6 km dengan terumbu karang dangkal dan padang lamun habitat duyung (Dugong).',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai Alami & Konservasi',
        'estimated_cost': 50000,
        'source': 'https://telukwondamakab.go.id/',
      },
      {
        'id': '3',
        'name': 'Gua Purba Pulau Misowaid & Air Terjun Maruni',
        'description': 'Melihat lukisan dinding cadas purba prasejarah di tebing karang laut serta air terjun segar di tepian hutan.',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Purbakala & Air Terjun',
        'estimated_cost': 30000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Kali Lemon Dive Resort Kwatisore',
        'type': 'Dive Resort',
        'location': 'Kwatisore, Nabire, Teluk Cenderawasih',
        'price_range': 'Rp1.200.000 - Rp2.500.000 / malam (full board)',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://telukcenderawasih.org/',
      },
      {
        'id': '2',
        'name': 'Grand Nabire Hotel',
        'type': 'Hotel',
        'location': 'Jl. Jenderal Sudirman No.17, Nabire',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://nabirekab.go.id/',
      },
      {
        'id': '3',
        'name': 'Wasior Beach Lodge',
        'type': 'Lodge',
        'location': 'Wasior, Teluk Wondama, Papua Barat',
        'price_range': 'Rp400.000 - Rp750.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://telukwondamakab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kuah Asam Kuning Nabire',
        'description': 'Ikan kakap merah perairan Teluk Cenderawasih berkuah asam kunyit segar dengan daun kemangi dan potongan tomat muda.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Bagan Kwatisore & Nabire',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://nabirekab.go.id/',
      },
      {
        'id': '2',
        'name': 'Sagu Lempeng & Ikan Asar Nabire',
        'description': 'Roti sagu bakar tradisional keras gurih dicelup kuah ikan asar cakalang asap yang gurih pedas nikmat.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Pasar Tradisional Kwatisore',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kepiting Bakau Saus Padang Papua',
        'description': 'Kepiting bakau bertelur tebal hasil tangkapan hutan mangrove pesisir dimasak saus pedas manis gurih melimpah.',
        'price_range': 'Rp60.000 - Rp120.000',
        'location': 'Resto Pantai Nabire',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 50. Pantai Ora
  DestinationDetailEntry(
    id: 50,
    shortDescription: 'Resor ramah lingkungan di atas air di tepi tebing karst Pulau Seram Maluku yang dijuluki Maldives-nya Indonesia.',
    attractions: [
      {
        'id': '1',
        'name': 'Snorkeling Terumbu Karang Ora Overwater',
        'description': 'Turun langsung dari tangga kamar vila di atas air ke perairan toska sebening kaca berisi terumbu karang warna-warni.',
        'image': 'https://images.unsplash.com/photo-1779828078188-21b0387c5c51?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari Overwater',
        'estimated_cost': 50000,
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Tebing Karst Sawai & Tebing Hatupia',
        'description': 'Gugusan tebing batu kapur vertikal megah yang berdiri kokoh di tengah birunya laut tenang Teluk Sawai.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Tebing Karst',
        'estimated_cost': 30000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Susur Sungai Salawai & Desa Adat Sawai',
        'description': 'Menyusuri sungai berkanopi hutan sagu alami dengan perahu ketinting menuju desa tertua di Pulau Seram.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Susur Sungai & Budaya',
        'estimated_cost': 100000,
        'source': 'https://malukuprov.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Ora Beach Eco Resort Water Villa',
        'type': 'Overwater Resort',
        'location': 'Pantai Ora, Sawai, Seram Utara, Maluku Tengah',
        'price_range': 'Rp1.500.000 - Rp2.900.000 / malam (full board)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Lisabiela Beach Resort Sawai',
        'type': 'Eco-Resort',
        'location': 'Desa Sawai, Seram Utara, Maluku Tengah',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Oa Guesthouse Sawai',
        'type': 'Homestay',
        'location': 'Desa Sawai, Teluk Sawai, Maluku Tengah',
        'price_range': 'Rp250.000 - Rp450.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Kuah Kuning & Papeda Maluku',
        'description': 'Ikan tongkol/kakap segar kuah kuning kunyit asam belimbing wuluh harum kemangi disantap bersama papeda sagu kenyal.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Ora Beach Resort & Desa Sawai',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://malukuprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Ikan Asar Cakalang Bumbu Colo-Colo',
        'description': 'Ikan cakalang segar diasap di atas bara batok kelapa disiram sambal colo-colo tomat, cabai rawit, dan perasan jeruk nipis.',
        'price_range': 'Rp30.000 - Rp55.000',
        'location': 'Sawai & Seram Utara',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kopi Rarobang Rempah Khas Maluku',
        'description': 'Kopi hitam khas rempah Maluku racikan jahe merah, cengkeh, kayu manis, dan taburan biji kenari sangrai gurih.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Kedai Tepi Laut Sawai',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),
];
