// ignore_for_file: lines_longer_than_80_chars
import 'destination_detail_entry.dart';

/// 1. Wilayah Java (ID 1-15)
final List<DestinationDetailEntry> javaDetails = [
  // 1. Candi Borobudur
  DestinationDetailEntry(
    id: 1,
    shortDescription: 'Candi Buddha abad ke-9 warisan wangsa Syailendra dengan relief megah dan stupa berlatar Gunung Merapi.',
    attractions: [
      {
        'id': '1',
        'name': 'Punthuk Setumbu Sunrise',
        'description': 'Bukit panorama terbaik untuk menyaksikan matahari terbit berpadu siluet Candi Borobudur berselimut kabut.',
        'image': 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam',
        'estimated_cost': 50000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Desa Wisata Candirejo',
        'description': 'Desa tradisional dengan tur dokar keliling kebun buah, belajar gamelan, dan kerajinan gerabah.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Budaya & Tradisi',
        'estimated_cost': 150000,
        'source': 'https://candirejo.com/',
      },
      {
        'id': '3',
        'name': 'Candi Mendut & Pawon',
        'description': 'Situs candi Buddha bersejarah yang berada dalam satu garis lurus filosofis dengan Candi Borobudur.',
        'image': 'https://images.unsplash.com/photo-1620549146396-9024d914cd99?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Sejarah',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Plataran Borobudur Resort & Spa',
        'type': 'Resort',
        'location': 'Tanjungan, Borobudur, Magelang',
        'price_range': 'Rp3.500.000 - Rp6.000.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://plataran.com/borobudur-resort/',
      },
      {
        'id': '2',
        'name': 'Sarasvati Borobudur Hotel',
        'type': 'Hotel',
        'location': 'Jl. Balaputradewa, Borobudur',
        'price_range': 'Rp650.000 - Rp1.200.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sarasvatiborobudur.com/',
      },
      {
        'id': '3',
        'name': 'Omah Ganjuran Homestay',
        'type': 'Homestay',
        'location': 'Borobudur, Magelang',
        'price_range': 'Rp250.000 - Rp450.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Mangut Beong Borobudur',
        'description': 'Olahan ikan beong khas Sungai Progo dengan kuah santan pedas gurih kaya rempah tradisional.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Kembanglimus, Borobudur',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Kupat Tahu Magelang',
        'description': 'Ketupat dengan tahu goreng, bakwan, tauge, kol, disiram kuah kacang manis gurih bercita rasa segar.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Kota Magelang',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://magelangkota.go.id/',
      },
      {
        'id': '3',
        'name': 'Nasi Lesah',
        'description': 'Kuliner khas Magelang berupa nasi berkuah soto santan hangat gurih dengan suwiran ayam kampung dan bihun.',
        'price_range': 'Rp12.000 - Rp20.000',
        'location': 'Pasar Rejowinangun, Magelang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://magelangkota.go.id/',
      },
    ],
  ),

  // 2. Candi Prambanan
  DestinationDetailEntry(
    id: 2,
    shortDescription: 'Kompleks candi Hindu tertinggi di Indonesia peninggalan Mataram Kuno dengan relief epos Ramayana.',
    attractions: [
      {
        'id': '1',
        'name': 'Sendratari Ramayana Prambanan',
        'description': 'Pertunjukan tari kolosal legendaris dengan latar belakang megah Candi Siwa di panggung terbuka.',
        'image': 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?q=80&w=800&auto=format&fit=crop',
        'category': 'Pertunjukan Seni',
        'estimated_cost': 150000,
        'source': 'https://borobudurpark.com/temple/prambanan/',
      },
      {
        'id': '2',
        'name': 'Candi Ratu Boko',
        'description': 'Situs gerbang keraton purba di atas bukit karst dengan panorama sunset terbaik di kawasan timur Yogyakarta.',
        'image': 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Sejarah',
        'estimated_cost': 40000,
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Candi Plaosan Kembar',
        'description': 'Kompleks candi kembar perpaduan Hindu-Buddha lambang cinta Rakai Pikatan dan Pramodawardhani.',
        'image': 'https://images.unsplash.com/photo-1620549146396-9024d914cd99?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Sejarah',
        'estimated_cost': 15000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Sheraton Mustika Yogyakarta Resort & Spa',
        'type': 'Resort',
        'location': 'Jl. Laksda Adisucipto, Sleman',
        'price_range': 'Rp1.100.000 - Rp2.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://marriott.com/yogsr',
      },
      {
        'id': '2',
        'name': 'Poeri Devata Resort Hotel',
        'type': 'Hotel',
        'location': 'Klodran, Prambanan, Sleman',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Prambanan Guesthouse',
        'type': 'Guesthouse',
        'location': 'Bokoharjo, Prambanan',
        'price_range': 'Rp200.000 - Rp350.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Gudeg Kalasan',
        'description': 'Gudeg basah manis gurih khas kawasan timur Sleman dengan lauk ayam kampung opor dan krecek pedas.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Kalasan, Sleman, Yogyakarta',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Ayam Goreng Kalasan',
        'description': 'Ayam goreng legendaris bertekstur empuk yang diungkep santan dan air kelapa dengan bumbu gurih meresap.',
        'price_range': 'Rp35.000 - Rp80.000',
        'location': 'Jl. Solo Km 14, Kalasan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://slemankab.go.id/',
      },
      {
        'id': '3',
        'name': 'Jadah Tempe Kaliurang',
        'description': 'Kombinasi uli ketan gurih kenyal dan tempe bacem legit khas lereng Gunung Merapi.',
        'price_range': 'Rp10.000 - Rp25.000',
        'location': 'Sleman, Yogyakarta',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
    ],
  ),

  // 3. Gunung Bromo
  DestinationDetailEntry(
    id: 3,
    shortDescription: 'Kawah vulkanik aktif spektakuler di tengah lautan pasir kaldera Tengger dengan sunrise Penanjakan yang tersohor.',
    attractions: [
      {
        'id': '1',
        'name': 'Sunrise Viewpoint Penanjakan 1',
        'description': 'Puncak panorama berketinggian 2.770 mdpl untuk menyaksikan matahari terbit berlatar Bromo, Batok, dan Semeru.',
        'image': 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam',
        'estimated_cost': 55000,
        'source': 'https://bromotenggersemeru.org/',
      },
      {
        'id': '2',
        'name': 'Lautan Pasir & Pasir Berbisik',
        'description': 'Hamparan padang pasir vulkanik seluas 5.250 hektar dengan sensasi berkendara jeep 4x4 dan menunggang kuda.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan',
        'estimated_cost': 200000,
        'source': 'https://bromotenggersemeru.org/',
      },
      {
        'id': '3',
        'name': 'Kawah Aktif Bromo & Pura Luhur Poten',
        'description': 'Mendaki 250 anak tangga menuju bibir kawah aktif serta mengagumi pura suci warga suku Tengger.',
        'image': 'https://images.unsplash.com/photo-1518458628499-27acd7f2c893?q=80&w=800&auto=format&fit=crop',
        'category': 'Eksplorasi Vulkanik',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Jiwa Jawa Resort Bromo',
        'type': 'Resort',
        'location': 'Wonotoro, Sukapura, Probolinggo',
        'price_range': 'Rp1.800.000 - Rp3.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://jiwajawa.com/bromo/',
      },
      {
        'id': '2',
        'name': 'Lava View Lodge',
        'type': 'Lodge',
        'location': 'Cemorolawang, Ngadisari',
        'price_range': 'Rp750.000 - Rp1.400.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bromotenggersemeru.org/',
      },
      {
        'id': '3',
        'name': 'Bromo Permai 1 Hotel',
        'type': 'Hotel',
        'location': 'Jl. Raya Bromo, Cemorolawang',
        'price_range': 'Rp500.000 - Rp900.000 / malam',
        'rating': 4.4,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatimur.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Nasi Rawon Probolinggo',
        'description': 'Sup daging sapi berkuah hitam kluwek khas Jawa Timur yang gurih mantap dengan sambal terasi dan taoge pendek.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Sukapura, Probolinggo',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disporapar.probolinggokab.go.id/',
      },
      {
        'id': '2',
        'name': 'Wedang Pokak Bromo',
        'description': 'Minuman herbal penghangat tubuh khas Tengger racikan jahe, cengkeh, kayu manis, dan serai beraroma wangi.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Cemorolawang, Bromo',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bromotenggersemeru.org/',
      },
      {
        'id': '3',
        'name': 'Bakso Malang Hangat',
        'description': 'Semangkuk bakso urat, tahu bakso, pangsit renyah dengan kaldu sapi gurih mendidih cocok di udara dingin pegunungan.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Kawasan Wisata Bromo',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 4. Kawah Ijen
  DestinationDetailEntry(
    id: 4,
    shortDescription: 'Danau kawah asam pirus terbesar di dunia yang menyuguhkan fenomena langka api biru (blue fire) dan tambang belerang.',
    attractions: [
      {
        'id': '1',
        'name': 'Fenomena Api Biru (Blue Fire)',
        'description': 'Pemandangan gas belerang menyala biru neon di dasar kawah yang hanya dapat disaksikan saat dini hari.',
        'image': 'https://images.unsplash.com/photo-1518458628499-27acd7f2c893?q=80&w=800&auto=format&fit=crop',
        'category': 'Fenomena Alam Langka',
        'estimated_cost': 100000,
        'source': 'https://banyuwangitourism.com/',
      },
      {
        'id': '2',
        'name': 'Danau Kawah Hijau Toska',
        'description': 'Danau kawah vulkanik air asam kuat seluas 54,66 hektar bergradasi warna toska memesona saat terbit matahari.',
        'image': 'https://images.unsplash.com/photo-1719556346386-4300480b7403?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Kawah',
        'estimated_cost': 50000,
        'source': 'https://banyuwangitourism.com/',
      },
      {
        'id': '3',
        'name': 'Hutan Mati Gandrung',
        'description': 'Jalur pendakian yang melintasi hamparan pepohonan eksotis khas vegetasi pegunungan vulkanik Jawa Timur.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Trekking',
        'estimated_cost': 30000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Ijen Resort and Villas',
        'type': 'Resort',
        'location': 'Randu Agung, Licin, Banyuwangi',
        'price_range': 'Rp1.500.000 - Rp2.800.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://ijenresortandvillas.com/',
      },
      {
        'id': '2',
        'name': 'Grand Harvest Resort & Villas',
        'type': 'Resort',
        'location': 'Tamansari, Licin, Banyuwangi',
        'price_range': 'Rp850.000 - Rp1.600.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://grandharvestresort.com/',
      },
      {
        'id': '3',
        'name': 'Paltuding Homestay Ijen',
        'type': 'Homestay',
        'location': 'Pos Paltuding, Licin',
        'price_range': 'Rp200.000 - Rp400.000 / malam',
        'rating': 4.3,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banyuwangitourism.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Sego Tempong Banyuwangi',
        'description': 'Nasi hangat dengan aneka sayuran rebus, lauk ikan asin, tempe, dan sambal tomat terasi ekstra pedas menampar.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Kota Banyuwangi',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banyuwangitourism.com/',
      },
      {
        'id': '2',
        'name': 'Rujak Soto Banyuwangi',
        'description': 'Perpaduan unik rujak sayur bumbu petis kacang yang disiram kuah soto babat daging sapi hangat gurih.',
        'price_range': 'Rp25.000 - Rp40.000',
        'location': 'Licin, Banyuwangi',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banyuwangikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pecel Pitik Suku Osing',
        'description': 'Ayam kampung bakar suwir berbumbu parutan kelapa muda, kemiri, terasi, dan cabai rawit khas adat Kemiren.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Desa Adat Kemiren, Banyuwangi',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://banyuwangitourism.com/',
      },
    ],
  ),

  // 5. Taman Nasional Karimunjawa
  DestinationDetailEntry(
    id: 5,
    shortDescription: 'Gugusan 27 pulau tropis di Laut Jawa berpasir putih bersih, terumbu karang terjaga, dan penangkaran hiu ramah.',
    attractions: [
      {
        'id': '1',
        'name': 'Snorkeling Terumbu Karang Pulau Menjangan Kecil',
        'description': 'Berenang di spot taman laut jernih dengan kawanan ikan badut (anemon) dan terumbu karang warna-warni.',
        'image': 'https://images.unsplash.com/photo-1619017107453-3d950380f0a9?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 175000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '2',
        'name': 'Pantai Ujung Gelam Sunset',
        'description': 'Pantai berpasir putih lembut dengan pohon kelapa miring ikonik dan pemandangan lembayung senja terbaik.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Pantai & Santai',
        'estimated_cost': 20000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Penangkaran Hiu Pulau Menjangan Besar',
        'description': 'Uji adrenalin dengan berfoto dan berenang bersama kawanan hiu sirip hitam (blacktip reef shark) jinak.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Bahari',
        'estimated_cost': 40000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Kura Kura Resort Karimunjawa',
        'type': 'Resort',
        'location': 'Pulau Menyawakan, Karimunjawa',
        'price_range': 'Rp3.200.000 - Rp6.500.000 / malam',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kurakuraresort.com/',
      },
      {
        'id': '2',
        'name': 'Breve Azurine Lagoon Resort',
        'type': 'Resort',
        'location': 'Kemujan, Karimunjawa',
        'price_range': 'Rp1.200.000 - Rp2.400.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://breveazurine.com/',
      },
      {
        'id': '3',
        'name': 'The Happinezz Karimunjawa',
        'type': 'Guesthouse',
        'location': 'Karimunjawa, Jepara',
        'price_range': 'Rp300.000 - Rp550.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Ikan Bakar Srepeh Karimun',
        'description': 'Ikan laut segar tangkapan nelayan dibakar dengan bumbu santan merah manis pedas menggugah selera.',
        'price_range': 'Rp40.000 - Rp80.000',
        'location': 'Alun-alun Karimunjawa',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Pindang Serani Jepara',
        'description': 'Sup ikan bandeng/kerapu kuah bening asam pedas segar dari belimbing wuluh, serai, daun kemangi, dan kunyit.',
        'price_range': 'Rp30.000 - Rp50.000',
        'location': 'Karimunjawa, Jepara',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://jepara.go.id/',
      },
      {
        'id': '3',
        'name': 'Bakso Ikan Ekor Kuning',
        'description': 'Bakso kenyal berbahan dasar murni daging ikan ekor kuning segar dengan kuah kaldu ikan gurih bening.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Dermaga Karimunjawa',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 6. Dataran Tinggi Dieng
  DestinationDetailEntry(
    id: 6,
    shortDescription: 'Negeri di atas awan bersuhu sejuk dengan kawah belerang Sikidang, Telaga Warna berkilau, dan Kompleks Candi Arjuna.',
    attractions: [
      {
        'id': '1',
        'name': 'Kompleks Candi Arjuna',
        'description': 'Kawasan candi Hindu tertua di Jawa abad ke-7 yang sering diselimuti embun upas es di pagi hari musim kemarau.',
        'image': 'https://images.unsplash.com/photo-1582298538104-fe2e74c27f59?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya',
        'estimated_cost': 20000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Telaga Warna & Telaga Pengilon',
        'description': 'Danau vulkanik kembar yang memancarkan pantulan gradasi warna hijau, toska, dan kuning keemasan memukau.',
        'image': 'https://images.unsplash.com/photo-1654862048364-72d809f46a76?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Alam',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Kawah Sikidang Dieng',
        'description': 'Kawah lumpur panas aktif yang berpindah-pindah dengan jembatan kayu estetik mengelilingi area vulkanik.',
        'image': 'https://images.unsplash.com/photo-1518458628499-27acd7f2c893?q=80&w=800&auto=format&fit=crop',
        'category': 'Vulkanik',
        'estimated_cost': 20000,
        'source': 'https://wonosobokab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Kresna Hotel Wonosobo',
        'type': 'Hotel',
        'location': 'Jl. Pasukan Ronggolawe, Wonosobo',
        'price_range': 'Rp650.000 - Rp1.100.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Dieng Cool Guesthouse',
        'type': 'Guesthouse',
        'location': 'Dieng Kulon, Batur, Banjarnegara',
        'price_range': 'Rp250.000 - Rp450.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wonosobokab.go.id/',
      },
      {
        'id': '3',
        'name': 'Homestay Arjuna Dieng',
        'type': 'Homestay',
        'location': 'Jl. Raya Dieng, Kejajar',
        'price_range': 'Rp200.000 - Rp350.000 / malam',
        'rating': 4.4,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Mie Ongklok Wonosobo',
        'description': 'Mie rebus berkuah kental pati gurih manis berpadu daun kucai, kol, dan sate sapi bumbu kacang lembut.',
        'price_range': 'Rp15.000 - Rp28.000',
        'location': 'Kota Wonosobo & Kawasan Dieng',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wonosobokab.go.id/',
      },
      {
        'id': '2',
        'name': 'Carica Khas Dieng',
        'description': 'Manisan buah pepaya gunung carica yang manis segar berkhasiat tinggi khas dataran tinggi Dieng.',
        'price_range': 'Rp15.000 - Rp35.000',
        'location': 'Kejajar, Wonosobo',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Tempe Kemul Dieng',
        'description': 'Tempe goreng tepung kunyit renyah hangat bertabur irisan kucai, nikmat disantap dengan cabai rawit hijau.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Pusat Kuliner Dieng',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://wonosobokab.go.id/',
      },
    ],
  ),

  // 7. Kota Lama Semarang
  DestinationDetailEntry(
    id: 7,
    shortDescription: 'Kawasan cagar budaya arsitektur kolonial Hindia Belanda abad ke-18 yang berjuluk Little Netherland.',
    attractions: [
      {
        'id': '1',
        'name': 'Gereja Blenduk (GPIB Immanuel)',
        'description': 'Gereja Kristen tertua di Jawa Tengah berkubah tembaga cembung peninggalan Belanda tahun 1753.',
        'image': 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?q=80&w=800&auto=format&fit=crop',
        'category': 'Bangunan Bersejarah',
        'estimated_cost': 10000,
        'source': 'https://pariwisata.semarangkota.go.id/',
      },
      {
        'id': '2',
        'name': 'Gedung Marba & Taman Srigunting',
        'description': 'Spot foto favorit bangunan bata merah bergaya neoklasik di sekeliling taman rindang yang asri.',
        'image': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop',
        'category': 'Cagar Budaya',
        'estimated_cost': 0,
        'source': 'https://pariwisata.semarangkota.go.id/',
      },
      {
        'id': '3',
        'name': 'Semarang Contemporary Art Gallery',
        'description': 'Galeri seni rupa modern bertempat di dalam gedung kolonial megah yang telah direvitalisasi indah.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Galeri Seni',
        'estimated_cost': 25000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Metro Park View Hotel Kota Lama',
        'type': 'Hotel',
        'location': 'Jl. KH. Agus Salim, Kota Lama, Semarang',
        'price_range': 'Rp600.000 - Rp1.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pariwisata.semarangkota.go.id/',
      },
      {
        'id': '2',
        'name': 'Spiegel Home & Hostel',
        'type': 'Hostel',
        'location': 'Jl. Letjen Suprapto, Kota Lama',
        'price_range': 'Rp250.000 - Rp500.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Hotel Kotta Semarang',
        'type': 'Hotel',
        'location': 'Taman Srigunting, Kota Lama',
        'price_range': 'Rp450.000 - Rp800.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://semarangkota.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Lumpia Semarang Basah & Goreng',
        'description': 'Kuliner legendaris berisi rebung muda manis gurih, daging ayam/udang, disajikan dengan saus cokelat kental.',
        'price_range': 'Rp15.000 - Rp30.000 / porsi',
        'location': 'Gang Lombok & Kota Lama',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pariwisata.semarangkota.go.id/',
      },
      {
        'id': '2',
        'name': 'Tahu Gimbal Semarang',
        'description': 'Potongan tahu goreng, gimbal udang renyah, tauge, kol, dan lontong disiram bumbu petis kacang gurih pekat.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Taman KB & Kota Lama',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://semarangkota.go.id/',
      },
      {
        'id': '3',
        'name': 'Asem-Asem Koh Liem',
        'description': 'Olahan daging sapi kuah asam segar berpadu belimbing wuluh, tomat hijau, dan cabai rawit pedas nikmat.',
        'price_range': 'Rp35.000 - Rp55.000',
        'location': 'Wonodri, Semarang',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
  ),

  // 8. Pantai Parangtritis
  DestinationDetailEntry(
    id: 8,
    shortDescription: 'Pantai legendaris pesisir selatan Yogyakarta dengan gumuk pasir pantai langka, tebing karang, dan matahari terbenam magis.',
    attractions: [
      {
        'id': '1',
        'name': 'Sandboarding di Gumuk Pasir Parangkusumo',
        'description': 'Berselancar di atas bukit pasir barchan langka yang bertipe serupa gurun pesisir dunia.',
        'image': 'https://images.unsplash.com/photo-1629605924917-d2de56a40951?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan Pesisir',
        'estimated_cost': 75000,
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Sunset Spot Tebing Paralayang Watugupit',
        'description': 'Gardu pandang di tebing tinggi untuk menikmati matahari terbenam memukau menghadap Samudra Hindia.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Sunset',
        'estimated_cost': 15000,
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Keliling Pantai Naik Dokar & ATV',
        'description': 'Menyusuri garis pantai pasir hitam membentang luas menggunakan kereta kuda tradisional dokar atau ATV.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Aktivitas Wisata',
        'estimated_cost': 50000,
        'source': 'https://bantulkab.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Queen of the South Resort',
        'type': 'Resort',
        'location': 'Jl. Parangrejo No.13, Parangtritis',
        'price_range': 'Rp950.000 - Rp2.200.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://queenofthesouthresort.com/',
      },
      {
        'id': '2',
        'name': 'Edge Resort Yogyakarta',
        'type': 'Resort',
        'location': 'Girijati, Purwosari, Gunungkidul/Bantul',
        'price_range': 'Rp1.200.000 - Rp2.600.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Puri Brata Resort & Gallery',
        'type': 'Villa',
        'location': 'Bantul, Yogyakarta',
        'price_range': 'Rp350.000 - Rp650.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bantulkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Sate Klatak Bantul',
        'description': 'Sate daging kambing muda empuk yang ditusuk jeruji besi sepeda dan dibumbui garam berkuah gulai gurih.',
        'price_range': 'Rp30.000 - Rp50.000',
        'location': 'Jl. Imogiri Timur, Bantul',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Peyek Undur-Undur Laut',
        'description': 'Camilan renyah gurih khas pantai selatan berbahan undur-undur laut (ketam pasir) berbalut adonan rempah.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Pesisir Parangtritis',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bantulkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Mie Des Pundong',
        'description': 'Mie kenyal olahan singkong khas Pundong Bantul dimasak pedas manis berkuah gurih beraroma ebi.',
        'price_range': 'Rp12.000 - Rp22.000',
        'location': 'Pundong, Bantul',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitingjogja.jogjaprov.go.id/',
      },
    ],
  ),

  // 9. Taman Nasional Ujung Kulon
  DestinationDetailEntry(
    id: 9,
    shortDescription: 'Situs Warisan Dunia UNESCO di ujung barat Jawa, habitat alami terakhir badak jawa bercula satu yang dilindungi.',
    attractions: [
      {
        'id': '1',
        'name': 'Pulau Peucang & Snorkeling Karang Copong',
        'description': 'Pulau berpasir putih selembut tepung dengan air laut toska jernih dan rusa liar yang ramah di bibir pantai.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi & Bahari',
        'estimated_cost': 250000,
        'source': 'http://tnujungkulon.menlhk.go.id/',
      },
      {
        'id': '2',
        'name': 'Canoeing Sungai Cigenter',
        'description': 'Menyusuri sungai berkanopi hutan hujan tropis lebat layaknya sungai Amazon mini di Pulau Handeuleum.',
        'image': 'https://images.unsplash.com/photo-1712024281674-ee4199ae2144?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan Sungai',
        'estimated_cost': 75000,
        'source': 'http://tnujungkulon.menlhk.go.id/',
      },
      {
        'id': '3',
        'name': 'Padang Savana Cidaon',
        'description': 'Menara pengamatan satwa untuk menyaksikan kawanan banteng liar jawa, merak hijau, dan burung eksotis.',
        'image': 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=800&auto=format&fit=crop',
        'category': 'Pengamatan Satwa',
        'estimated_cost': 50000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Peucang Island Eco Resort',
        'type': 'Eco-Resort',
        'location': 'Pulau Peucang, TN Ujung Kulon',
        'price_range': 'Rp950.000 - Rp1.800.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'http://tnujungkulon.menlhk.go.id/',
      },
      {
        'id': '2',
        'name': 'Ciputih Resort Ujung Kulon',
        'type': 'Resort',
        'location': 'Sumur, Pandeglang, Banten',
        'price_range': 'Rp550.000 - Rp950.000 / malam',
        'rating': 4.4,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.bantenprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Homestay Desa Kertajaya Sumur',
        'type': 'Homestay',
        'location': 'Kecamatan Sumur, Pandeglang',
        'price_range': 'Rp200.000 - Rp350.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pandeglangkab.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Angeun Lada Banten',
        'description': 'Sayur daging sapi berkuah santan merah pedas khas pandeglang dengan aroma khas daun walang yang khas.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Sumur & Pandeglang',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://dispar.bantenprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Sate Bandeng Tanpa Duri',
        'description': 'Ikan bandeng olahan rempah santan tanpa duri yang dipanggang dalam jepitan bambu beraroma harum asap.',
        'price_range': 'Rp35.000 - Rp60.000',
        'location': 'Pandeglang / Serang, Banten',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bantenprov.go.id/',
      },
      {
        'id': '3',
        'name': 'Ikan Bakar Bumbu Sumur',
        'description': 'Ikan kuwe/kakap laut segar hasil tangkapan nelayan lokal yang dibakar dengan olesan bumbu kecap rempah.',
        'price_range': 'Rp40.000 - Rp75.000',
        'location': 'Dermaga Sumur, Pandeglang',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 10. Kepulauan Seribu
  DestinationDetailEntry(
    id: 10,
    shortDescription: 'Gugusan pulau karang tropis di Teluk Jakarta yang menawarkan pelarian santai snorkeling, diving, dan sunset pantai.',
    attractions: [
      {
        'id': '1',
        'name': 'Pulau Pelangi & Pulau Macan Eco Resort',
        'description': 'Pulau resor bernuansa alami dengan pantai air bening dan konservasi terumbu karang hidup.',
        'image': 'https://images.unsplash.com/photo-1682107222295-aebd076e2afb?q=80&w=800&auto=format&fit=crop',
        'category': 'Wisata Bahari',
        'estimated_cost': 350000,
        'source': 'https://pulauseribu.jakarta.go.id/',
      },
      {
        'id': '2',
        'name': 'Jembatan Cinta Pulau Tidung',
        'description': 'Jembatan ikonik sepanjang 800 meter yang menghubungkan Tidung Besar dan Kecil dengan spot loncat indah ke laut.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Ikon Wisata',
        'estimated_cost': 15000,
        'source': 'https://pulauseribu.jakarta.go.id/',
      },
      {
        'id': '3',
        'name': 'Taman Nasional Laut Pulau Pramuka & Konservasi Penyu',
        'description': 'Melihat penangkaran tukik penyu sisik dan menjelajahi ekosistem hutan mangrove hijau di pesisir pulau.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Satwa',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Pulau Macan Eco Village & Resort',
        'type': 'Eco-Resort',
        'location': 'Pulau Macan, Kepulauan Seribu Utara',
        'price_range': 'Rp2.400.000 - Rp4.500.000 / malam (all-in)',
        'rating': 4.9,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pulaumacana.com/',
      },
      {
        'id': '2',
        'name': 'Asha Resort Pulau Payung',
        'type': 'Glamping Resort',
        'location': 'Pulau Payung, Kepulauan Seribu',
        'price_range': 'Rp1.500.000 - Rp2.900.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pulauseribu.jakarta.go.id/',
      },
      {
        'id': '3',
        'name': 'Homestay Tidung Beach View',
        'type': 'Homestay',
        'location': 'Pulau Tidung, Kepulauan Seribu',
        'price_range': 'Rp300.000 - Rp600.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://jakarta.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Pindang Kuning Ikan Tongkol Pulau',
        'description': 'Sup ikan kuah kuning segar dengan bumbu kunyit, daun kemangi, asam jawa, dan potongan cabai rawit merah.',
        'price_range': 'Rp25.000 - Rp45.000',
        'location': 'Pulau Pramuka & Pulau Tidung',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pulauseribu.jakarta.go.id/',
      },
      {
        'id': '2',
        'name': 'Kue Selingkuh Kepulauan Seribu',
        'description': 'Kue tradisional berbahan beras ketan pulen berisi abon ikan gurih yang dibungkus daun pisang harum.',
        'price_range': 'Rp5.000 - Rp10.000 / buah',
        'location': 'Pulau Panggang & Pramuka',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://jakarta.go.id/',
      },
      {
        'id': '3',
        'name': 'Cumi Bakar Saus Madu Pesisir',
        'description': 'Cumi-cumi segar hasil tangkapan nelayan malam hari dibakar empuk dengan polesan saus kecap madu gurih.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Pujasera Pulau Pramuka',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 11. Kawah Putih Ciwidey
  DestinationDetailEntry(
    id: 11,
    shortDescription: 'Danau vulkanik belerang kawah Gunung Patuha dengan air putih kehijauan yang berubah warna dan suasana magis berkabut.',
    attractions: [
      {
        'id': '1',
        'name': 'Dermaga Ponton & Skywalk Cantigi',
        'description': 'Jembatan kayu di atas danau kawah dan jembatan gantung kanopi hutan pohon cantigi yang instagramable.',
        'image': 'https://images.unsplash.com/photo-1719556346386-4300480b7403?q=80&w=800&auto=format&fit=crop',
        'category': 'Spot Foto & Panorama',
        'estimated_cost': 25000,
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Kebun Teh Rancabali & Glamping Lakeside',
        'description': 'Hamparan perkebunan teh hijau berkabut sejuk dengan pemandangan Situ Patenggang dan resto Pinisi megah.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Agrowisata Alam',
        'estimated_cost': 50000,
        'source': 'https://bandungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pemandian Air Panas Alami Cimanggu & Ciwalini',
        'description': 'Berendam air panas alami kaya mineral belerang di tengah sejuknya lembah pegunungan teh Ciwidey.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Pemandian Relaksasi',
        'estimated_cost': 35000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Glamping Lakeside Rancabali',
        'type': 'Glamping',
        'location': 'Jl. Raya Ciwidey - Patengan No.Km. 39',
        'price_range': 'Rp1.100.000 - Rp2.300.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'eMTe Highland Resort Ciwidey',
        'type': 'Resort',
        'location': 'Jl. Raya Ciwidey - Rancabali Km 11',
        'price_range': 'Rp550.000 - Rp1.100.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bandungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Driam Riverside Resort',
        'type': 'Resort',
        'location': 'Jl. Raya Soreang-Ciwidey Km 25',
        'price_range': 'Rp650.000 - Rp1.400.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://driamriverside.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Nasi Liwet Sunda Kastrol',
        'description': 'Nasi liwet gurih rempah serai, daun salam, dan teri medan disajikan dengan lalapan, sambal terasi, dan tahu tempe.',
        'price_range': 'Rp35.000 - Rp65.000',
        'location': 'Resto Khas Sunda Ciwidey',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Bandrek Kelapa Muda Hanjuang',
        'description': 'Minuman tradisional penghangat tubuh dari jahe merah, gula aren, kayu manis, dan kerukan kelapa muda legit.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Kawasan Kawah Putih & Rancabali',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://bandungkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Strawberry Petik Sendiri Ciwidey',
        'description': 'Menikmati buah stroberi segar organik manis asam hasil petik langsung dari kebun agrowisata lokal.',
        'price_range': 'Rp30.000 - Rp60.000 / kg',
        'location': 'Jl. Raya Ciwidey - Patengan',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 12. Kebun Raya Bogor
  DestinationDetailEntry(
    id: 12,
    shortDescription: 'Kebun botani tertua di Asia Tenggara seluas 87 hektar dengan koleksi ribuan tanaman tropis di samping Istana Kepresidenan Bogor.',
    attractions: [
      {
        'id': '1',
        'name': 'Taman Astrid & Danau Gunting Teratai',
        'description': 'Hamparan padang rumput hijau luas berlatar danau teratai raksasa Victoria amazonica dan Istana Bogor.',
        'image': 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop',
        'category': 'Taman Botani',
        'estimated_cost': 25000,
        'source': 'https://kebunraya.id/bogor',
      },
      {
        'id': '2',
        'name': 'Griya Anggrek & Taman Meksiko',
        'description': 'Koleksi ratusan spesies anggrek endemik Indonesia serta taman kaktus sukulen bertema gurun eksotis.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Tanaman',
        'estimated_cost': 15000,
        'source': 'https://kebunraya.id/bogor',
      },
      {
        'id': '3',
        'name': 'Museum Zoologi Bogor',
        'description': 'Museum fauna bersejarah dengan koleksi jutaan spesimen satwa liar, termasuk kerangka paus biru raksasa.',
        'image': 'https://images.unsplash.com/photo-1582426007790-f5a2e2392dd3?q=80&w=800&auto=format&fit=crop',
        'category': 'Museum & Edukasi',
        'estimated_cost': 25000,
        'source': 'https://kotabogor.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'The Sahira Hotel Bogor',
        'type': 'Hotel',
        'location': 'Jl. Ahmad Yani No.17-23, Tanah Sareal',
        'price_range': 'Rp650.000 - Rp1.300.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kotabogor.go.id/',
      },
      {
        'id': '2',
        'name': 'Royal Hotel Bogor',
        'type': 'Hotel',
        'location': 'Jl. Ir. H. Juanda No.16, Paledang',
        'price_range': 'Rp500.000 - Rp950.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://hotelroyalbogor.com/',
      },
      {
        'id': '3',
        'name': 'Novotel Bogor Golf Resort & Convention',
        'type': 'Resort',
        'location': 'Golf Estate Bogor Raya, Sukaraja',
        'price_range': 'Rp1.100.000 - Rp2.400.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://accor.com/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Soto Mie Bogor Asli',
        'description': 'Semangkuk mie kuning dengan potongan daging sapi, risoles renyah, tomat, kol, berkuah kaldu merah gurih segar.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Jl. Surya Kencana, Bogor',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kotabogor.go.id/',
      },
      {
        'id': '2',
        'name': 'Doclang Khas Bogor',
        'description': 'Pesona kuliner legendaris berisi ketupat daun patat, kentang rebus, tahu kuning, disiram bumbu kacang kental manis.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Jembatan Merah & Surya Kencana',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kotabogor.go.id/',
      },
      {
        'id': '3',
        'name': 'Asinan Jagung Bakar Surya Kencana',
        'description': 'Serutan jagung manis bakar disiram kuah asinan cuka cabai asam pedas manis berpadu kerupuk mie kuning.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Jl. Surya Kencana No. 289, Bogor',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),

  // 13. Taman Safari Indonesia Puncak
  DestinationDetailEntry(
    id: 13,
    shortDescription: 'Konservasi satwa liar kelas dunia di kawasan Puncak berhawa sejuk di mana satwa hidup bebas di habitat alaminya.',
    attractions: [
      {
        'id': '1',
        'name': 'Safari Journey Satwa Bebas',
        'description': 'Berkendara menyusuri habitat satwa liar 5 benua secara langsung dari dalam mobil atau bus safari tertutup.',
        'image': 'https://images.unsplash.com/photo-1615220682566-4992e5a7082b?q=80&w=800&auto=format&fit=crop',
        'category': 'Safari Satwa Liar',
        'estimated_cost': 230000,
        'source': 'https://tamansafari.com/bogor',
      },
      {
        'id': '2',
        'name': 'Istana Panda Indonesia',
        'description': 'Kandang konservasi sejuk di ketinggian 1.800 mdpl untuk menyaksikan sepasang Giant Panda asal Tiongkok.',
        'image': 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?q=80&w=800&auto=format&fit=crop',
        'category': 'Konservasi Langka',
        'estimated_cost': 0,
        'source': 'https://tamansafari.com/bogor',
      },
      {
        'id': '3',
        'name': 'Night Safari & Atraksi Teater Satwa',
        'description': 'Sensasi menjelajahi kehidupan binatang nokturnal di malam hari dengan kereta terbuka berlampu khusus.',
        'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan Malam',
        'estimated_cost': 180000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Safari Resort Taman Safari',
        'type': 'Resort',
        'location': 'Jl. Kapten Harun Kabir No. 724, Cisarua',
        'price_range': 'Rp1.200.000 - Rp2.800.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://tamansafari.com/safari-resort/',
      },
      {
        'id': '2',
        'name': 'Pesona Alam Resort & Spa',
        'type': 'Resort',
        'location': 'Jl. Taman Safari No. 101, Cisarua, Bogor',
        'price_range': 'Rp1.100.000 - Rp2.500.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://pesonaalamresort.com/',
      },
      {
        'id': '3',
        'name': 'Caravan Lodge Safari',
        'type': 'Lodge',
        'location': 'Kawasan TSI Cisarua, Bogor',
        'price_range': 'Rp750.000 - Rp1.500.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://tamansafari.com/bogor',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Sate Kambing Muda Puncak',
        'description': 'Sate kambing muda empuk juicy dengan bumbu kecap cabai rawit pedas dan kuah sop kaki kambing berkaldu gurih.',
        'price_range': 'Rp45.000 - Rp75.000',
        'location': 'Jl. Raya Puncak, Cisarua',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kotabogor.go.id/',
      },
      {
        'id': '2',
        'name': 'Jagung Bakar Manis & Sekoteng Puncak',
        'description': 'Jagung manis bakar aneka rasa disantap bersama sekoteng kuah jahe hangat di tengah udara dingin malam Puncak.',
        'price_range': 'Rp15.000 - Rp25.000',
        'location': 'Puncak Pass, Cisarua',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
      {
        'id': '3',
        'name': 'Gemblong Gula Aren Hangat',
        'description': 'Kue ketan putih gurih berbalut gula merah tebu karamel manis legit yang baru matang digoreng.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Kios Oleh-Oleh Puncak',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
    ],
  ),

  // 14. Pantai Menganti
  DestinationDetailEntry(
    id: 14,
    shortDescription: 'Pantai tersembunyi dengan perpaduan spektakuler tebing karst hijau menjulang, mercusuar putih, dan pasir pantai putih bersih.',
    attractions: [
      {
        'id': '1',
        'name': 'Tanjung Karangbata & Jembatan Merah',
        'description': 'Tebing batuan karang purba yang menjorok ke samudra dengan deburan ombak besar dan jembatan gantung panorama.',
        'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
        'category': 'Panorama Tebing',
        'estimated_cost': 20000,
        'source': 'https://disparbud.kebumenkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Mercusuar Kuno Peninggalan Belanda',
        'description': 'Mercusuar putih bersejarah setinggi 20 meter buatan tahun 1886 dengan lanskap 360 derajat pantai selatan.',
        'image': 'https://images.unsplash.com/photo-1629605924917-d2de56a40951?q=80&w=800&auto=format&fit=crop',
        'category': 'Situs Sejarah',
        'estimated_cost': 10000,
        'source': 'https://kebumenkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Lembah Menguneng & Shuttle Wisata',
        'description': 'Menyusuri jalanan perbukitan karst hijau menghadap birunya laut lepas menggunakan shuttle mobil bak terbuka.',
        'image': 'https://images.unsplash.com/photo-1685975875980-f19fbd4d36a6?q=80&w=800&auto=format&fit=crop',
        'category': 'Petualangan Pesisir',
        'estimated_cost': 20000,
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Menganti Cliff View Villa',
        'type': 'Villa',
        'location': 'Desa Karangduwur, Ayah, Kebumen',
        'price_range': 'Rp500.000 - Rp950.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.kebumenkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Mexolie Hotel Kebumen',
        'type': 'Hotel',
        'location': 'Jl. Stasiun No.8, Panjer, Kebumen',
        'price_range': 'Rp450.000 - Rp850.000 / malam',
        'rating': 4.7,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kebumenkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Homestay Pantai Ayah',
        'type': 'Homestay',
        'location': 'Kecamatan Ayah, Kebumen',
        'price_range': 'Rp180.000 - Rp350.000 / malam',
        'rating': 4.4,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Seafood Bakar Segar Pantai Ayah',
        'description': 'Ikan kakap, udang windu, dan cumi segar hasil tangkapan nelayan TPI Ayah dibakar bumbu rujak pedas gurih.',
        'price_range': 'Rp40.000 - Rp80.000',
        'location': 'Warung Pesisir Menganti & Ayah',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.kebumenkab.go.id/',
      },
      {
        'id': '2',
        'name': 'Nasi Penggel Kebumen',
        'description': 'Nasi kepal bulat lembut disajikan dengan sayur nangka muda kuah santan gurih dan lauk jeroan/kikil sapi empuk.',
        'price_range': 'Rp15.000 - Rp28.000',
        'location': 'Pusat Kuliner Kebumen',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://kebumenkab.go.id/',
      },
      {
        'id': '3',
        'name': 'Sate Ambal Bumbu Tempe',
        'description': 'Sate ayam kampung khas pesisir selatan berlumur saus unik berbahan dasar tempe kedelai rebus yang dihaluskan.',
        'price_range': 'Rp25.000 - Rp40.000',
        'location': 'Kecamatan Ambal, Kebumen',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://visitjawatengah.jatengprov.go.id/',
      },
    ],
  ),

  // 15. Kampung Adat Ciptagelar
  DestinationDetailEntry(
    id: 15,
    shortDescription: 'Kampung adat kasepuhan Sunda Banten Kidul berusia lebih dari 600 tahun yang memegang teguh tradisi leluhur bertani padi.',
    attractions: [
      {
        'id': '1',
        'name': 'Upacara Seren Taun & Leuit Padi',
        'description': 'Ritual syukur panen raya tahunan dan mengagumi ratusan lumbung padi kayu tradisional (leuit) yang tahan puluhan tahun.',
        'image': 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
        'category': 'Tradisi Adat',
        'estimated_cost': 50000,
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Imah Gede & Arsitektur Rumah Panggung',
        'description': 'Pusat kediaman Abah Uki (ketua adat) berstruktur kayu dan bambu alami tanpa paku yang ramah gempa.',
        'image': 'https://images.unsplash.com/photo-1643785879507-11a0c02205da?q=80&w=800&auto=format&fit=crop',
        'category': 'Arsitektur Budaya',
        'estimated_cost': 20000,
        'source': 'https://sukabumikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Pembangkit Listrik Mikrohidro Mandiri',
        'description': 'Melihat inovasi kemandirian energi warga adat yang memanfaatkan aliran air sungai pegunungan Halimun Salak.',
        'image': 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=800&auto=format&fit=crop',
        'category': 'Ekowisata Edukasi',
        'estimated_cost': 20000,
        'source': 'https://indonesia.travel/',
      },
    ],
    accommodations: [
      {
        'id': '1',
        'name': 'Homestay Rumah Adat Kasepuhan Ciptagelar',
        'type': 'Homestay',
        'location': 'Desa Sirnaresmi, Cisolok, Sukabumi',
        'price_range': 'Rp150.000 - Rp300.000 / malam',
        'rating': 4.8,
        'image': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Grand Inna Samudra Beach Palabuhanratu',
        'type': 'Resort',
        'location': 'Jl. Raya Cisolok - Pelabuhanratu KM.7',
        'price_range': 'Rp750.000 - Rp1.500.000 / malam',
        'rating': 4.6,
        'image': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sukabumikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Ocean Queen Resort Cisolok',
        'type': 'Resort',
        'location': 'Cikahuripan, Cisolok, Sukabumi',
        'price_range': 'Rp600.000 - Rp1.200.000 / malam',
        'rating': 4.5,
        'image': 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
    ],
    localFoods: [
      {
        'id': '1',
        'name': 'Nasi Beras Merah Beureum Ciptagelar',
        'description': 'Nasi beras merah organik pulen varietas lokal warisan ratusan tahun hasil panen alami tanpa pupuk kimia.',
        'price_range': 'Rp20.000 - Rp35.000',
        'location': 'Dapur Adat Ciptagelar',
        'image': 'https://images.unsplash.com/photo-1596450514735-3769c3a37651?q=80&w=800&auto=format&fit=crop',
        'source': 'https://disparbud.jabarprov.go.id/',
      },
      {
        'id': '2',
        'name': 'Pepes Ikan Sungai Bumbu Kunyit',
        'description': 'Ikan sungai segar dibumbui kunyit, daun kemangi, serai, dan cabai rawit dibungkus daun pisang lalu dibakar bara.',
        'price_range': 'Rp25.000 - Rp40.000',
        'location': 'Kasepuhan Ciptagelar',
        'image': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
        'source': 'https://sukabumikab.go.id/',
      },
      {
        'id': '3',
        'name': 'Kopi Robusta Pegunungan Halimun',
        'description': 'Kopi robusta tubruk petik merah yang ditanam di lereng hutan Halimun dengan rasa pekat beraroma cokelat tanah.',
        'price_range': 'Rp10.000 - Rp20.000',
        'location': 'Kasepuhan Ciptagelar',
        'image': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
        'source': 'https://indonesia.travel/',
      },
    ],
  ),
];
